spring.application.name=auth-service
server.port= 9080

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL:http://auth.dev.localhost}/realms/${KEYCLOAK_REALM:dalai-llama}

spring.management.endpoints.web.exposure.include= health, info
spring.endpoint.health.show-details= always

keycloak.realm= dalai-llama
keycloak.realm.admin.url= http://auth.dev.localhost
keycloak.admin.client-id=auth-service
keycloak.admin.client-secret=${AUTH_CLIENT_SECRET:change-me}