package com.dalai.llama.creator.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.util.*;

@Entity
@Table(name = "creator_storyboard_chat_messages")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreatorStoryboardChatMessage {

    @Id
    private UUID id;

    @Column(name = "workspace_id", nullable = false)
    private UUID workspaceId;

    /**
     * User
     * Assistant
     * System
     */
    @Column(nullable = false, length = 20)
    private String role;

    @Column(columnDefinition = "text")
    private String message;

    /**
     * AI understanding.
     */
    @Builder.Default
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "intent_payload",
            columnDefinition = "jsonb")
    private Map<String,Object> intentPayload = new LinkedHashMap<>();

    /**
     * Operations generated by AI.
     */
    @Builder.Default
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "operations",
            columnDefinition = "jsonb")
    private List<Map<String,Object>> operations = new ArrayList<>();

    /**
     * Which shots changed.
     */
    @Builder.Default
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "affected_shots",
            columnDefinition = "jsonb")
    private List<Integer> affectedShots = new ArrayList<>();

    /**
     * Assistant reply.
     */
    @Column(columnDefinition = "text")
    private String assistantResponse;

    /**
     * Workspace version this turn produced, or null for a Q&A-only turn
     * that didn't change anything.
     */
    @Column(name = "applied_version")
    private Integer appliedVersion;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;
}
