apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: predictions
spec:
  selector:
    app: prediction-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
