-- Full camera/position/lens/composition/focus/movement/support/exposure/temporal/filtration/
-- image-character taxonomy, prefixed cine_ to distinguish from the existing summary-level
-- camera_angle/camera_movement/lens_suggestion fields (both stay -- the cine_ group is the
-- granular breakdown a DP critic reasons about contradictions with).
ALTER TABLE shot
    ADD COLUMN cine_camera_body VARCHAR(160),
    ADD COLUMN cine_sensor VARCHAR(160),
    ADD COLUMN cine_capture_format VARCHAR(160),
    ADD COLUMN cine_recording_characteristics TEXT,
    ADD COLUMN cine_position_height VARCHAR(160),
    ADD COLUMN cine_position_distance VARCHAR(160),
    ADD COLUMN cine_position_lateral VARCHAR(160),
    ADD COLUMN cine_position_elevation VARCHAR(160),
    ADD COLUMN cine_position_orientation VARCHAR(160),
    ADD COLUMN cine_lens_focal_length VARCHAR(80),
    ADD COLUMN cine_lens_type VARCHAR(80),
    ADD COLUMN cine_lens_optical_format VARCHAR(80),
    ADD COLUMN cine_lens_distortion VARCHAR(160),
    ADD COLUMN cine_lens_compression VARCHAR(160),
    ADD COLUMN cine_lens_character TEXT,
    ADD COLUMN cine_framing TEXT,
    ADD COLUMN cine_subject_placement VARCHAR(160),
    ADD COLUMN cine_headroom VARCHAR(80),
    ADD COLUMN cine_lead_room VARCHAR(80),
    ADD COLUMN cine_visual_balance TEXT,
    ADD COLUMN cine_focus_target VARCHAR(160),
    ADD COLUMN cine_focus_distance VARCHAR(80),
    ADD COLUMN cine_depth_of_field VARCHAR(80),
    ADD COLUMN cine_rack_focus TEXT,
    ADD COLUMN cine_focus_behaviour TEXT,
    ADD COLUMN cine_movement_type VARCHAR(160),
    ADD COLUMN cine_movement_trajectory TEXT,
    ADD COLUMN cine_movement_speed VARCHAR(80),
    ADD COLUMN cine_movement_acceleration VARCHAR(80),
    ADD COLUMN cine_movement_rotation VARCHAR(160),
    ADD COLUMN cine_movement_subject_relationship TEXT,
    ADD COLUMN cine_support VARCHAR(160),
    ADD COLUMN cine_aperture VARCHAR(80),
    ADD COLUMN cine_iso VARCHAR(80),
    ADD COLUMN cine_shutter VARCHAR(80),
    ADD COLUMN cine_nd_filter VARCHAR(80),
    ADD COLUMN cine_dynamic_range VARCHAR(160),
    ADD COLUMN cine_shutter_angle VARCHAR(80),
    ADD COLUMN cine_motion_blur VARCHAR(160),
    ADD COLUMN cine_slow_motion VARCHAR(160),
    ADD COLUMN cine_filtration_diffusion VARCHAR(160),
    ADD COLUMN cine_filtration_nd VARCHAR(80),
    ADD COLUMN cine_filtration_polarizer VARCHAR(80),
    ADD COLUMN cine_filtration_specialty VARCHAR(160),
    ADD COLUMN cine_contrast VARCHAR(160),
    ADD COLUMN cine_color_response VARCHAR(160),
    ADD COLUMN cine_grain VARCHAR(160),
    ADD COLUMN cine_halation VARCHAR(160),
    ADD COLUMN cine_bloom VARCHAR(160),
    ADD COLUMN cine_sharpness VARCHAR(160),
    ADD COLUMN cine_flare VARCHAR(160);
