package com.dalai.llama.billing.domain.entity.enums;

public enum UsageMetric {
    INBOUND_CALL_MINUTES,
    OUTBOUND_CALL_MINUTES,
    AI_STT_SECONDS,
    AI_LLM_TOKENS,
    AI_VIDEO_SECONDS,
    AI_VIDEO_MILLION_PIXELS,
    AI_VIDEO_CREDITS,
    AI_AUDIO_SECONDS,
    AI_AUDIO_CHARACTERS,
    AI_MUSIC_CLIPS,
    AI_PROVIDER_USAGE,
    DID_RENTAL,
    DID_SETUP,
    RECORDING_STORAGE_GB,
    SMS_SENT,
    SMS_RECEIVED
}
