version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8082:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      OPEN_AI_API_KEY: sk-proj-oCV1d5OP2E1WNwkR0f8bT3BlbkFJPSjeCs8wEJfEdEGMiVeY
      SERP_API_KEY: 7c4a91d98646880ba279c6c30fa9a14dbd32c2b0f8ce77d416c6759b3a37120f