package com.dalai.llama.pbx.core.util;

import com.dalai.llama.pbx.core.model.SignalingConfig;
import com.dalai.llama.pbx.core.model.Tenant;
import org.springframework.stereotype.Component;

/**
 * Minimal TURN config for tenant.
 */
@Component
public class CoturnConfigBuilder {

    public String build(Tenant t, SignalingConfig cfg) {
        String realm = cfg.getTurnRealm() == null ? "turn." + (t.getName() == null ? "example" : t.getName()) : cfg.getTurnRealm();
        String external = cfg.getTurnFqdn() == null ? "0.0.0.0" : cfg.getTurnFqdn();

        return String.join("\n",
                "# Coturn autogenerated for tenant " + t.getId(),
                "realm=" + realm,
                "external-ip=" + external,
                "fingerprint",
                "lt-cred-mech",
                "total-quota=0",
                "no-loopback-peers",
                "no-multicast-peers",
                ""
        );
    }
}
