package com.dalai.llama.pbx.core.util;

import com.dalai.llama.pbx.core.model.Did;
import com.dalai.llama.pbx.core.model.IvrDtmfMap;
import com.dalai.llama.pbx.core.model.IvrNode;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Builds FreeSWITCH dialplan XML with IVR nodes, bot hooks, recording and conference points.
 */
@Component
public class DynamicFreeSwitchDialplanBuilder {

    private final IvrTreeBuilder ivrTreeBuilder;
    private final BotForkBuilder botForkBuilder;
    private final ConferenceBuilder conferenceBuilder;

    public DynamicFreeSwitchDialplanBuilder(IvrTreeBuilder ivrTreeBuilder,
                                            BotForkBuilder botForkBuilder,
                                            ConferenceBuilder conferenceBuilder) {
        this.ivrTreeBuilder = ivrTreeBuilder;
        this.botForkBuilder = botForkBuilder;
        this.conferenceBuilder = conferenceBuilder;
    }

    public String buildDialplan(String tenantId,
                                List<Did> dids,
                                List<IvrNode> ivrNodes,
                                boolean aiEnabled) {

        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<include>\n");

        // Inbound entry that maps DID -> IVR entry or default
        sb.append("  <extension name=\"inbound-").append(tenantId).append("\">\n");
        sb.append("    <condition field=\"destination_number\" expression=\"(.*)\">\n");
        sb.append("      <action application=\"answer\"/>\n");
        sb.append("      <action application=\"set\" data=\"RECORD_STEREO=true\"/>\n");
        sb.append("      <action application=\"record_session\" data=\"/var/lib/freeswitch/recordings/")
                .append(tenantId).append("/${uuid}.wav\"/>\n");

        // Try mapping DID to explicit entrypoint in DB (passed via Did.entrypoint)
        if (dids != null && !dids.isEmpty()) {
            for (Did d : dids) {
                if (d.getNumber() == null || d.getEntrypoint() == null) continue;
                sb.append("      <condition field=\"destination_number\" expression=\"^")
                        .append(d.getNumber()).append("$\">\n");
                sb.append("        <action application=\"transfer\" data=\"")
                        .append(d.getEntrypoint()).append(" XML ivr-").append(tenantId).append("\"/>\n");
                sb.append("      </condition>\n");
            }
        }

        // default: transfer to main IVR or hangup
        sb.append("      <action application=\"transfer\" data=\"main XML ivr-").append(tenantId).append("\"/>\n");
        sb.append("    </condition>\n");
        sb.append("  </extension>\n\n");

        // Add bot for AI hook if enabled
        if (aiEnabled) {
            sb.append(botForkBuilder.buildAIForkXml(tenantId)).append("\n");
        }

        // Add conference template
        sb.append(conferenceBuilder.buildConferenceXml(tenantId)).append("\n");

        // Append IVR tree
        sb.append(ivrTreeBuilder.buildIvr(tenantId, ivrNodes)).append("\n");

        sb.append("</include>\n");
        return sb.toString();
    }

    public String buildDialplan(String tenantId, List<IvrNode> nodes) {

        Map<String, IvrNode> map = nodes.stream()
                .collect(Collectors.toMap(IvrNode::getNodeId, n -> n));

        StringBuilder sb = new StringBuilder();
        sb.append("<include>\n");
        sb.append("  <!-- Autogenerated Dialplan for Tenant ").append(tenantId).append(" -->\n");

        // Root entry: IVR @ pbx-core → “ivr_main_{{tenantId}}”
        sb.append("""
          <extension name="tenant-%s-ivr">
            <condition field="destination_number" expression="ivr_main">
              <action application="transfer" data="ivr_main_%s XML default"/>
            </condition>
          </extension>
        """.formatted(tenantId, tenantId));

        // Build per-node IVR menus
        for (IvrNode node : nodes) {
            sb.append(buildNode(tenantId, node, map));
        }

        sb.append("</include>\n");
        return sb.toString();
    }

    private String buildNode(String tenantId, IvrNode node, Map<String,IvrNode> map) {

        String id = node.getNodeId();
        String name = "ivr_%s_%s".formatted(id, tenantId);

        StringBuilder sb = new StringBuilder();
        sb.append("\n  <!-- IVR Node: ").append(id).append(" -->\n");

        sb.append("  <extension name=\"").append(name).append("\">\n");
        sb.append("    <condition field=\"destination_number\" expression=\"").append(name).append("\">\n");

        // Play prompt
        sb.append("      <action application=\"playback\" data=\"")
                .append(node.getPrompt() == null ? "silence_stream://1000" : node.getPrompt())
                .append("\"/>\n");

        // If AI bot enabled
        if (node.isBotEnabled()) {
            sb.append("      <action application=\"lua\" data=\"ai_bot.lua ")
                    .append(tenantId).append(" ").append(id)
                    .append("\"/>\n");
        }

        // If final node → transfer directly
        if (node.isFinalNode()) {
            sb.append("      <action application=\"transfer\" data=\"")
                    .append(node.getTransferNumber())
                    .append(" XML default\"/>\n");
        }

        // DTMF children
        if (node.getDtmfMappings() != null && !node.getDtmfMappings().isEmpty()) {
            for (IvrDtmfMap d : node.getDtmfMappings()) {

                String key = d.getDtmfKey();          // 1,2,3,0,*
                String tgt = d.getNextNode();         // next IVR nodeId

                sb.append("""
                  <action application="bind_digit_action" data="%s,ivr_%s_%s,XML,default"/>
                """.formatted(
                        key,
                        tgt,
                        tenantId
                ));
            }
        }

        // Looping on invalid input
        sb.append("      <action application=\"playback\" data=\"ivr/ivr-that_was_an_invalid_entry.wav\"/>\n");
        sb.append("      <action application=\"transfer\" data=\"").append(name).append(" XML default\"/>\n");

        sb.append("    </condition>\n");
        sb.append("  </extension>\n");

        return sb.toString();
    }
}
