package com.dalai.llama.creativeplanning.service.storage;

import com.dalai.llama.creativeplanning.service.CreativePlanningException;
import io.minio.GetObjectArgs;
import io.minio.GetPresignedObjectUrlArgs;
import io.minio.MinioClient;
import io.minio.PutObjectArgs;
import io.minio.http.Method;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.ByteArrayInputStream;
import java.util.concurrent.TimeUnit;

/** The one place this service talks to MinIO -- every upload path (reference images, project-
 * requirement attachments, exported PDFs) goes through here instead of repeating put/sign logic.
 * Multipart uploads stream directly from the request's own input stream (never buffered whole
 * into a byte[]); server-generated bytes (a rendered PDF) are small and already fully in memory
 * by the time they reach here, so {@link #uploadBytes} takes a byte[] directly. */
@Component
public class MinioObjectStorage {

    private final MinioClient minioClient;
    private final MinioClient publicMinioClient;
    private final String bucket;

    public MinioObjectStorage(
            MinioClient minioClient,
            @Qualifier("publicMinioClient") MinioClient publicMinioClient,
            @Value("${creative-planning.minio.bucket}") String bucket
    ) {
        this.minioClient = minioClient;
        this.publicMinioClient = publicMinioClient;
        this.bucket = bucket;
    }

    public String bucket() {
        return bucket;
    }

    public void uploadMultipart(String objectKey, MultipartFile file, String contentType) {
        try (var inputStream = file.getInputStream()) {
            minioClient.putObject(PutObjectArgs.builder()
                    .bucket(bucket)
                    .object(objectKey)
                    .stream(inputStream, file.getSize(), -1)
                    .contentType(contentType)
                    .build());
        } catch (Exception ex) {
            throw CreativePlanningException.upstream("Could not upload to MinIO: " + ex.getMessage());
        }
    }

    public void uploadBytes(String objectKey, byte[] bytes, String contentType) {
        try {
            minioClient.putObject(PutObjectArgs.builder()
                    .bucket(bucket)
                    .object(objectKey)
                    .stream(new ByteArrayInputStream(bytes), bytes.length, -1)
                    .contentType(contentType)
                    .build());
        } catch (Exception ex) {
            throw CreativePlanningException.upstream("Could not upload to MinIO: " + ex.getMessage());
        }
    }

    /** Re-fetches a previously uploaded object's bytes -- used by the deferred reference-image
     * analysis flow, which stores an image at creation time but only reads it back (to build the
     * vision LLM's data URI) once the requirement is funded. */
    public byte[] downloadBytes(String objectKey) {
        try (var stream = minioClient.getObject(GetObjectArgs.builder()
                .bucket(bucket)
                .object(objectKey)
                .build())) {
            return stream.readAllBytes();
        } catch (Exception ex) {
            throw CreativePlanningException.upstream("Could not download from MinIO: " + ex.getMessage());
        }
    }

    public String signedUrl(String objectKey) {
        try {
            return publicMinioClient.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder()
                    .method(Method.GET)
                    .bucket(bucket)
                    .object(objectKey)
                    .expiry(1, TimeUnit.HOURS)
                    .build());
        } catch (Exception ex) {
            throw CreativePlanningException.upstream("Could not sign MinIO URL: " + ex.getMessage());
        }
    }
}
