package com.dalai.llama.creativeplanning.service.requirement;

import com.dalai.llama.creativeplanning.domain.IdeaOptionSource;
import com.dalai.llama.creativeplanning.domain.entity.IdeaOption;
import com.dalai.llama.creativeplanning.domain.entity.LockedIdea;
import com.dalai.llama.creativeplanning.dto.IdeaOptionView;
import com.dalai.llama.creativeplanning.dto.LockedIdeaView;
import com.dalai.llama.creativeplanning.repository.IdeaOptionRepository;
import com.dalai.llama.creativeplanning.repository.LockedIdeaRepository;
import com.dalai.llama.creativeplanning.service.CreativePlanningException;
import com.dalai.llama.creativeplanning.service.generation.JsonExtraction;
import com.dalai.llama.creativeplanning.service.llmgateway.LlmGatewayChatRequest;
import com.dalai.llama.creativeplanning.service.llmgateway.LlmGatewayChatRequest.LlmGatewayMessage;
import com.dalai.llama.creativeplanning.service.llmgateway.LlmGatewayChatResponse;
import com.dalai.llama.creativeplanning.service.llmgateway.LlmGatewayClient;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * The "switch to a different idea" counterpart of {@link ProjectRequirementIdeaService}, for a
 * project that already exists (as opposed to a not-yet-funded {@code ProjectRequirement}).
 * Candidates are generated by diverging from the project's CURRENT idea rather than originating
 * from a funding brief -- see {@code PROJECT_IDEA_ALTERNATIVES} vs {@code
 * PROJECT_REQUIREMENT_IDEA_GENERATION}. Same persistence philosophy as that class: every
 * candidate generate() returns is saved immediately, and picking one never mutates anything --
 * it creates a brand new {@link LockedIdea} row and repoints the project at it, leaving every
 * earlier idea (and everything generated under it) exactly as it was.
 */
@Service
public class ProjectIdeaService {

    private static final String GENERATE_TASK_KEY = "PROJECT_IDEA_ALTERNATIVES";
    private static final int DEFAULT_OPTION_COUNT = 3;

    private final IdeaOptionRepository ideaOptionRepository;
    private final LockedIdeaRepository lockedIdeaRepository;
    private final PreProductionServiceClient preProductionServiceClient;
    private final LlmGatewayClient llmGatewayClient;
    private final ObjectMapper objectMapper;
    private final String defaultModel;

    public ProjectIdeaService(
            IdeaOptionRepository ideaOptionRepository,
            LockedIdeaRepository lockedIdeaRepository,
            PreProductionServiceClient preProductionServiceClient,
            LlmGatewayClient llmGatewayClient,
            ObjectMapper objectMapper,
            @Value("${creative-planning.llm-gateway.default-text-model}") String defaultModel
    ) {
        this.ideaOptionRepository = ideaOptionRepository;
        this.lockedIdeaRepository = lockedIdeaRepository;
        this.preProductionServiceClient = preProductionServiceClient;
        this.llmGatewayClient = llmGatewayClient;
        this.objectMapper = objectMapper;
        this.defaultModel = defaultModel;
    }

    /** Diverges from the project's current idea into {@code count} alternatives, persisting each
     * immediately (source=GENERATED) same as {@link ProjectRequirementIdeaService#generateOptions}. */
    @Transactional
    public List<IdeaOptionView> generateOptions(UUID tenantId, UUID projectId, Integer count) {
        LockedIdea current = requireCurrentIdea(tenantId, projectId);
        int optionCount = (count == null || count < 1) ? DEFAULT_OPTION_COUNT : Math.min(count, 5);

        LlmGatewayChatResponse response = llmGatewayClient.chat(
                tenantId.toString(),
                "project-idea-alternatives-" + projectId + "-" + UUID.randomUUID(),
                new LlmGatewayChatRequest(defaultModel, List.of(new LlmGatewayMessage("user", "")),
                        JsonExtraction.JSON_MODE_PARAMS, GENERATE_TASK_KEY,
                        java.util.Map.of(
                                "title", current.getTitle(),
                                "concept", orNotSpecified(current.getConcept()),
                                "targetAudience", orNotSpecified(current.getTargetAudience()),
                                "campaignAngle", orNotSpecified(current.getCampaignAngle()),
                                "keyMessage", orNotSpecified(current.getKeyMessage()),
                                "tone", orNotSpecified(current.getTone()),
                                "optionCount", String.valueOf(optionCount)
                        )));

        OffsetDateTime now = OffsetDateTime.now();
        List<IdeaOption> saved = parseCandidates(response).stream()
                .map(candidate -> ideaOptionRepository.save(IdeaOption.builder()
                        .tenantId(tenantId)
                        .projectId(projectId)
                        .title(candidate.title())
                        .concept(candidate.concept())
                        .targetAudience(candidate.targetAudience())
                        .campaignAngle(candidate.campaignAngle())
                        .keyMessage(candidate.keyMessage())
                        .tone(candidate.tone())
                        .source(IdeaOptionSource.GENERATED)
                        .parentId(null)
                        .createdAt(now)
                        .build()))
                .collect(Collectors.toList());

        return saved.stream().map(this::toOptionView).collect(Collectors.toList());
    }

    /** Every option ever generated for this project, newest first -- same "survives a page
     * refresh" reasoning as {@link ProjectRequirementIdeaService#listOptions}. */
    @Transactional(readOnly = true)
    public List<IdeaOptionView> listOptions(UUID tenantId, UUID projectId) {
        return ideaOptionRepository.findByProjectIdOrderByCreatedAtDesc(projectId).stream()
                .filter(option -> option.getTenantId().equals(tenantId))
                .map(this::toOptionView)
                .collect(Collectors.toList());
    }

    /** Creates a new LockedIdea from the chosen option and repoints the project at it -- never
     * mutates the option or the idea it's replacing. Script/Screenplay/Shot generation on
     * pre-production-service's side each stamp their own row with whatever the project currently
     * points to, so this one repoint is the entire mechanism; nothing else here needs to know or
     * care what was generated under the old idea. */
    @Transactional
    public LockedIdeaView switchToOption(UUID tenantId, UUID projectId, UUID ideaOptionId) {
        IdeaOption option = ideaOptionRepository.findByIdAndTenantId(ideaOptionId, tenantId)
                .orElseThrow(() -> CreativePlanningException.notFound("No idea option " + ideaOptionId));
        if (!projectId.equals(option.getProjectId())) {
            throw CreativePlanningException.badRequest("Idea option " + ideaOptionId + " does not belong to project " + projectId);
        }
        LockedIdea current = requireCurrentIdea(tenantId, projectId);

        LockedIdea lockedIdea = lockedIdeaRepository.save(LockedIdea.builder()
                .tenantId(tenantId)
                .projectId(projectId)
                .title(option.getTitle())
                .concept(option.getConcept())
                .targetAudience(option.getTargetAudience())
                .campaignAngle(option.getCampaignAngle())
                .keyMessage(option.getKeyMessage())
                .tone(option.getTone())
                .budgetTier(current.getBudgetTier())
                .createdAt(OffsetDateTime.now())
                .build());

        preProductionServiceClient.switchLockedIdea(tenantId, projectId, lockedIdea.getId());

        return toView(lockedIdea);
    }

    private LockedIdea requireCurrentIdea(UUID tenantId, UUID projectId) {
        LockedIdea current = lockedIdeaRepository.findTopByProjectIdOrderByCreatedAtDesc(projectId)
                .orElseThrow(() -> CreativePlanningException.notFound("No locked idea for project " + projectId));
        if (!current.getTenantId().equals(tenantId)) {
            throw CreativePlanningException.notFound("No locked idea for project " + projectId);
        }
        return current;
    }

    private static String orNotSpecified(String value) {
        return (value == null || value.isBlank()) ? "Not specified" : value;
    }

    /** Raw shape the LLM actually returns -- same as {@link ProjectRequirementIdeaService}'s. */
    private record RawIdeaCandidate(
            String title,
            String concept,
            String targetAudience,
            String campaignAngle,
            String keyMessage,
            String tone
    ) {
    }

    private List<RawIdeaCandidate> parseCandidates(LlmGatewayChatResponse response) {
        if (response == null || response.response() == null || response.response().isBlank()) {
            throw CreativePlanningException.upstream("llm-gateway returned no content for " + GENERATE_TASK_KEY);
        }
        try {
            return objectMapper.readValue(
                    JsonExtraction.stripCodeFence(response.response()),
                    new TypeReference<List<RawIdeaCandidate>>() {
                    });
        } catch (Exception ex) {
            throw CreativePlanningException.upstream("Could not parse " + GENERATE_TASK_KEY + " response as JSON: " + ex.getMessage());
        }
    }

    /** No critic-service scoring for this flow yet (switching an already-created project's idea)
     * -- only the standalone-brief path ({@code ProjectRequirementIdeaService}) is wired to
     * critic-service today, so every score field here is null/empty, same as any option generated
     * before that feature shipped. */
    private IdeaOptionView toOptionView(IdeaOption option) {
        return new IdeaOptionView(option.getId(), option.getTitle(), option.getConcept(), option.getTargetAudience(),
                option.getCampaignAngle(), option.getKeyMessage(), option.getTone(), option.getSource(),
                option.getParentId(), null, null, null, null, List.of(), List.of(), option.getCreatedAt());
    }

    private LockedIdeaView toView(LockedIdea idea) {
        return new LockedIdeaView(idea.getId(), idea.getSessionId(), idea.getTitle(), idea.getConcept(),
                idea.getTargetAudience(), idea.getCampaignAngle(), idea.getKeyMessage(), idea.getTone(),
                idea.getBudgetTier(), idea.getCreatedAt());
    }
}
