package com.dalai.llama.pbx.core.repository.core;


import com.dalai.llama.pbx.core.domain.entity.core.TenantDialplan;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Tenant dialplan — pre-generated FreeSWITCH XML stored per tenant.
 *
 * THE critical read path:
 *   FreeSWITCH mod_xml_curl → GET /internal/freeswitch/dialplan?context=tenant_{slug}
 *   → FreeSwitchXmlController → findByContext() → returns dialplan_xml
 *
 * This is called on EVERY call that reaches FreeSWITCH. The context column
 * has a UNIQUE index (from V6 migration) for fast lookup.
 *
 * Write path:
 *   tenant-service → POST /api/v1/write/tenant-dialplan
 *   The XML is generated by tenant-service based on product code and features.
 */
@Repository
public interface TenantDialplanRepository extends JpaRepository<TenantDialplan, UUID> {

    /**
     * THE runtime query — mod_xml_curl sends context as query param.
     * Context format: "tenant_{slug}" e.g., "tenant_acme_corp"
     */
    Optional<TenantDialplan> findByContext(String context);

    Optional<TenantDialplan> findByTenantId(UUID tenantId);

    boolean existsByContext(String context);

    boolean existsByTenantId(UUID tenantId);

    @Modifying
    void deleteByTenantId(UUID tenantId);
}
