package com.dalai.llama.tenant.service.provisioning.telecom.config;

import com.dalai.llama.tenant.domain.entity.Tenant;
import com.dalai.llama.tenant.service.provisioning.telecom.model.TelecomStackConfig;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * Production-ready Kamailio configuration builder.
 * 
 * Features:
 * - SBC functionality with trunk selection
 * - WebRTC gateway (WSS + DTLS-SRTP via RTPEngine)
 * - Agent registration with external auth (agent-service)
 * - DID routing to PBX-Core for IVR/Queue decisions
 * - Outbound click-to-call via JSON-RPC
 * - Kafka event publishing (registration, call events)
 * - NAT traversal with RTPEngine
 * - TLS/SRTP support
 */
@Slf4j
@Component
public class KamailioConfigBuilder {

    public String build(Tenant tenant, TelecomStackConfig config) {
        log.info("Building Kamailio config for tenant {}", tenant.getSlug());
        
        StringBuilder sb = new StringBuilder();
        
        // Header and defines
        sb.append(buildDefines(tenant, config));
        
        // Module loading
        sb.append(buildModuleLoading(config));
        
        // Module parameters
        sb.append(buildModuleParams(config));
        
        // Listeners
        sb.append(buildListeners(config));
        
        // Main request routing
        sb.append(buildRequestRoute(config));
        
        // Secondary routes
        sb.append(buildSecondaryRoutes(config));
        
        // Event routes
        sb.append(buildEventRoutes(config));
        
        // Failure and reply routes
        sb.append(buildFailureRoutes());
        
        return sb.toString();
    }
    
    private String buildDefines(Tenant tenant, TelecomStackConfig config) {
        return String.format("""
            #!KAMAILIO
            # ============================================================
            # Kamailio SBC Configuration
            # Tenant: %s
            # Realm: %s
            # Generated: Auto-generated by Dalai LLAMA Platform
            # ============================================================
            
            #!define TENANT_ID "%s"
            #!define TENANT_SLUG "%s"
            #!define TENANT_REALM "%s"
            #!define PBX_CORE_URL "%s"
            #!define AGENT_AUTH_URL "%s"
            #!define AI_SERVICE_URL "%s"
            #!define RTPENGINE_SOCK "%s"
            #!define KAFKA_BROKERS "%s"
            #!define KAFKA_REG_TOPIC "%s"
            #!define KAFKA_CALL_TOPIC "%s"
            #!define ESL_HOST "freeswitch"
            #!define ESL_PORT %d
            #!define ESL_PASSWORD "%s"
            
            # Feature flags
            #!define WITH_WEBSOCKET
            #!define WITH_NAT
            #!define WITH_RTPENGINE
            #!define WITH_TLS
            #!define WITH_KAFKA
            #!define WITH_ASYNC_HTTP
            %s
            
            # Debug settings
            debug=3
            log_stderror=no
            memdbg=5
            memlog=5
            
            # Fork settings
            fork=yes
            children=4
            
            # TCP settings
            tcp_connection_lifetime=3605
            tcp_accept_no_cl=yes
            tcp_rd_buf_size=16384
            
            """,
                tenant.getSlug(),
                config.getRealm(),
                config.getTenantId(),
                config.getTenantSlug(),
                config.getRealm(),
                config.getPbxCoreUrl(),
                config.getAgentServiceUrl(),
                config.getAiServiceUrl(),
                config.getRtpEngineSocket(),
                config.getKafkaBootstrap(),
                config.getKafkaRegistrationTopic(),
                config.getKafkaCallTopic(),
                config.getEslPort(),
                config.getEslPassword(),
                config.isEnableAiTranscription() ? "#!define WITH_AI_TRANSCRIPTION" : ""
        );
    }
    
    private String buildModuleLoading(TelecomStackConfig config) {
        return """
            # ============================================================
            # MODULE LOADING
            # ============================================================
            
            # Core modules
            loadmodule "kex.so"
            loadmodule "corex.so"
            loadmodule "tm.so"
            loadmodule "tmx.so"
            loadmodule "sl.so"
            loadmodule "rr.so"
            loadmodule "pv.so"
            loadmodule "maxfwd.so"
            loadmodule "textops.so"
            loadmodule "textopsx.so"
            loadmodule "siputils.so"
            loadmodule "xlog.so"
            loadmodule "sanity.so"
            loadmodule "ctl.so"
            loadmodule "cfg_rpc.so"
            loadmodule "jsonrpcs.so"
            loadmodule "jansson.so"
            
            # SIP registration
            loadmodule "usrloc.so"
            loadmodule "registrar.so"
            
            # Authentication
            loadmodule "auth.so"
            
            # Dialog tracking
            loadmodule "dialog.so"
            
            # NAT traversal
            loadmodule "nathelper.so"
            loadmodule "rtpengine.so"
            
            # Dispatcher for trunk selection
            loadmodule "dispatcher.so"
            
            # HTTP client for async PBX calls
            loadmodule "http_client.so"
            loadmodule "http_async_client.so"
            
            # TLS
            loadmodule "tls.so"
            
            # WebSocket
            loadmodule "websocket.so"
            loadmodule "xhttp.so"
            
            # Kafka events
            loadmodule "kafka.so"
            
            # UAC for outbound auth
            loadmodule "uac.so"
            
            # Pike for rate limiting
            loadmodule "pike.so"
            loadmodule "htable.so"
            
            # Regex for DID matching
            loadmodule "regex.so"
            
            # SDPOPS for SDP manipulation
            loadmodule "sdpops.so"
            
            """;
    }
    
    private String buildModuleParams(TelecomStackConfig config) {
        return String.format("""
            # ============================================================
            # MODULE PARAMETERS
            # ============================================================
            
            # -- TLS params --
            modparam("tls", "config", "/etc/kamailio/tls.cfg")
            modparam("tls", "tls_force_run", 1)
            
            # -- RTPEngine params --
            modparam("rtpengine", "rtpengine_sock", RTPENGINE_SOCK)
            modparam("rtpengine", "rtpengine_disable_tout", 20)
            modparam("rtpengine", "rtpengine_retr", 2)
            
            # -- Dispatcher params --
            modparam("dispatcher", "list_file", "/etc/kamailio/dispatcher.list")
            modparam("dispatcher", "flags", 2)
            modparam("dispatcher", "dst_avp", "$avp(ds_dst)")
            modparam("dispatcher", "grp_avp", "$avp(ds_grp)")
            modparam("dispatcher", "cnt_avp", "$avp(ds_cnt)")
            modparam("dispatcher", "dstid_avp", "$avp(ds_dstid)")
            modparam("dispatcher", "ds_probing_mode", 1)
            modparam("dispatcher", "ds_ping_interval", 30)
            
            # -- Usrloc params --
            modparam("usrloc", "db_mode", 0)
            modparam("usrloc", "nat_bflag", 6)
            modparam("usrloc", "use_domain", 1)
            
            # -- Registrar params --
            modparam("registrar", "method_filtering", 1)
            modparam("registrar", "max_expires", 3600)
            modparam("registrar", "min_expires", 60)
            modparam("registrar", "default_expires", 600)
            modparam("registrar", "gruu_enabled", 0)
            
            # -- Dialog params --
            modparam("dialog", "dlg_flag", 4)
            modparam("dialog", "track_cseq_updates", 1)
            modparam("dialog", "event_callback", "ksr_dialog_event")
            
            # -- NAT helper params --
            modparam("nathelper", "natping_interval", 30)
            modparam("nathelper", "ping_nated_only", 1)
            modparam("nathelper", "sipping_bflag", 7)
            modparam("nathelper", "sipping_from", "sip:pinger@" TENANT_REALM)
            
            # -- HTTP async client params --
            modparam("http_async_client", "workers", 4)
            modparam("http_async_client", "connection_timeout", 2000)
            modparam("http_async_client", "curl_verbose", 0)
            
            # -- Kafka params --
            modparam("kafka", "brokers", KAFKA_BROKERS)
            modparam("kafka", "configuration", "socket.keepalive.enable=true")
            
            # -- WebSocket params --
            modparam("websocket", "keepalive_mechanism", 1)
            modparam("websocket", "keepalive_timeout", 30)
            modparam("websocket", "keepalive_processes", 1)
            modparam("websocket", "keepalive_interval", 5)
            
            # -- Pike rate limiting --
            modparam("pike", "sampling_time_unit", 10)
            modparam("pike", "reqs_density_per_unit", 30)
            modparam("pike", "remove_latency", 120)
            
            # -- HTable for blacklist --
            modparam("htable", "htable", "ipban=>size=8;autoexpire=300;")
            
            # -- UAC for outbound trunk auth --
            modparam("uac", "reg_db_table", "uacreg")
            modparam("uac", "reg_contact_addr", TENANT_REALM)
            
            # -- JSONRPCS for CLI/API --
            modparam("jsonrpcs", "pretty_format", 1)
            modparam("jsonrpcs", "fifo_name", "/run/kamailio/kamailio_rpc.fifo")
            
            """, config.getTenantSlug());
    }
    
    private String buildListeners(TelecomStackConfig config) {
        return String.format("""
            # ============================================================
            # LISTENERS
            # ============================================================
            
            # UDP/TCP SIP
            listen=udp:0.0.0.0:%d advertise %s:%d
            listen=tcp:0.0.0.0:%d advertise %s:%d
            
            # TLS SIP
            listen=tls:0.0.0.0:%d advertise %s:%d
            
            # WebSocket (WSS for WebRTC)
            listen=tls:0.0.0.0:%d advertise %s:%d
            
            # Enable TCP for SIP over WebSocket
            tcp_accept_no_cl=yes
            
            """,
                config.getSipUdpPort(), "${EXTERNAL_IP}", config.getSipUdpPort(),
                config.getSipTcpPort(), "${EXTERNAL_IP}", config.getSipTcpPort(),
                config.getSipTlsPort(), "${EXTERNAL_IP}", config.getSipTlsPort(),
                config.getWssPort(), "${EXTERNAL_IP}", config.getWssPort()
        );
    }
    
    private String buildRequestRoute(TelecomStackConfig config) {
        return """
            # ============================================================
            # MAIN REQUEST ROUTING
            # ============================================================
            
            request_route {
                # Per-request initialization
                route(REQINIT);
                
                # NAT detection
                route(NATDETECT);
                
                # CANCEL processing
                if (is_method("CANCEL")) {
                    if (t_check_trans()) {
                        route(RELAY);
                    }
                    exit;
                }
                
                # Handle retransmissions
                if (!is_method("ACK")) {
                    if (t_precheck_trans()) {
                        t_check_trans();
                        exit;
                    }
                    t_check_trans();
                }
                
                # Handle requests within dialogs
                route(WITHINDLG);
                
                # Record-route for all requests
                if (is_method("INVITE|SUBSCRIBE")) {
                    record_route();
                }
                
                # Dispatch to specific handlers
                if (is_method("REGISTER")) {
                    route(REGISTRAR);
                    exit;
                }
                
                if (is_method("OPTIONS")) {
                    route(OPTIONS);
                    exit;
                }
                
                if (is_method("INVITE")) {
                    route(INVITE);
                    exit;
                }
                
                if (is_method("REFER")) {
                    route(REFER);
                    exit;
                }
                
                if (is_method("NOTIFY|SUBSCRIBE")) {
                    route(PRESENCE);
                    exit;
                }
                
                if (is_method("MESSAGE")) {
                    route(MESSAGE);
                    exit;
                }
                
                # Default: reject
                sl_send_reply(405, "Method Not Allowed");
                exit;
            }
            
            """;
    }
    
    private String buildSecondaryRoutes(TelecomStackConfig config) {
        return """
            # ============================================================
            # SECONDARY ROUTES
            # ============================================================
            
            # --- Request initialization ---
            route[REQINIT] {
                # Rate limiting
                if (src_ip != myself) {
                    if ($sht(ipban=>$si) != $null) {
                        xdbg("Blocked IP: $si\\n");
                        exit;
                    }
                    if (!pike_check_req()) {
                        xlog("L_ALERT", "PIKE blocking $si\\n");
                        $sht(ipban=>$si) = 1;
                        exit;
                    }
                }
                
                # Max forwards check
                if (!mf_process_maxfwd_header("10")) {
                    sl_send_reply(483, "Too Many Hops");
                    exit;
                }
                
                # Sanity checks
                if (!sanity_check("17895", "7")) {
                    xlog("L_WARN", "Malformed SIP from $si:$sp\\n");
                    exit;
                }
                
                # Anti-flood for INVITE/REGISTER
                if (is_method("INVITE|REGISTER|SUBSCRIBE")) {
                    if ($ua =~ "friendly|scanner|sipcli|sipvicious|sundayddr|iWar|CSipSimple|Onalytica") {
                        xlog("L_WARN", "Blocked scanner: $ua from $si\\n");
                        exit;
                    }
                }
            }
            
            # --- NAT detection and handling ---
            route[NATDETECT] {
                force_rport();
                if (nat_uac_test("19")) {
                    if (is_method("REGISTER")) {
                        fix_nated_register();
                    } else {
                        if (is_first_hop()) {
                            set_contact_alias();
                        }
                    }
                    setflag(5);  # NAT flag
                }
            }
            
            # --- WebSocket detection ---
            route[WSDETECT] {
                if (proto == WS || proto == WSS) {
                    $var(is_webrtc) = 1;
                    setflag(8);  # WebRTC flag
                } else {
                    $var(is_webrtc) = 0;
                }
            }
            
            # --- OPTIONS handling (health check) ---
            route[OPTIONS] {
                if ($ru =~ "health" || $rU == "health") {
                    sl_send_reply(200, "OK");
                    exit;
                }
                sl_send_reply(200, "OK");
                exit;
            }
            
            # --- REGISTER handling ---
            route[REGISTRAR] {
                route(WSDETECT);
                
                # WebSocket contacts need alias
                if (isflagset(8)) {
                    fix_nated_register();
                    set_contact_alias();
                }
                
                # Check for Authorization header
                if ($hdr(Authorization) == "") {
                    www_challenge(TENANT_REALM, "0");
                    exit;
                }
                
                # Async auth to agent-service
                $var(auth_body) = "{" +
                    "\\"username\\":\\"" + $au + "\\"," +
                    "\\"realm\\":\\"" + TENANT_REALM + "\\"," +
                    "\\"tenantId\\":\\"" + TENANT_ID + "\\"," +
                    "\\"nonce\\":\\"" + $an + "\\"," +
                    "\\"uri\\":\\"" + $tu + "\\"," +
                    "\\"response\\":\\"" + $ar + "\\"," +
                    "\\"method\\":\\"" + $rm + "\\"," +
                    "\\"isWebRtc\\":" + $var(is_webrtc) +
                "}";
                
                http_async_query(
                    AGENT_AUTH_URL "/api/v1/tenants/" TENANT_ID "/agents/sip/auth",
                    $var(auth_body),
                    "AUTH_REPLY"
                );
                exit;
            }
            
            # --- Auth reply handler ---
            route[AUTH_REPLY] {
                if ($http_ok && $http_rs == 200) {
                    # Auth successful - save registration
                    if (!save("location")) {
                        sl_reply_error();
                        exit;
                    }
                    
                    # Publish registration event to Kafka
                    $var(reg_event) = "{" +
                        "\\"tenantId\\":\\"" + TENANT_ID + "\\"," +
                        "\\"aor\\":\\"" + $tu + "\\"," +
                        "\\"contact\\":\\"" + $ct + "\\"," +
                        "\\"expires\\":" + $hdr(Expires) + "," +
                        "\\"userAgent\\":\\"" + $ua + "\\"," +
                        "\\"sourceIp\\":\\"" + $si + "\\"," +
                        "\\"eventType\\":\\"REGISTER\\"" +
                    "}";
                    kafka_send(KAFKA_REG_TOPIC, $tu, $var(reg_event));
                    
                    exit;
                }
                
                if ($http_rs == 401) {
                    www_challenge(TENANT_REALM, "0");
                    exit;
                }
                
                if ($http_rs == 403 || $http_rs == 404) {
                    sl_send_reply(403, "Forbidden");
                    exit;
                }
                
                xlog("L_ERR", "Auth error: $http_rs - $http_rb\\n");
                sl_send_reply(500, "Auth Server Error");
                exit;
            }
            
            # --- INVITE handling ---
            route[INVITE] {
                route(WSDETECT);
                
                # Set dialog flag for tracking
                setflag(4);
                
                # RTPEngine early engagement for WebRTC
                if (isflagset(8)) {
                    rtpengine_manage("replace-origin replace-session-connection ICE=force DTLS=passive");
                } else {
                    rtpengine_manage("replace-origin replace-session-connection");
                }
                
                # Add custom headers
                append_hf("X-Tenant-Id: " + TENANT_ID + "\\r\\n");
                append_hf("X-Realm: " + TENANT_REALM + "\\r\\n");
                
                # Check if inbound (from trunk) or outbound (from agent)
                if ($fU =~ "^\\\\+?[0-9]+$" || src_ip == myself) {
                    # Inbound call from PSTN - route to PBX-Core
                    route(INBOUND_CALL);
                } else {
                    # Outbound call from registered agent
                    if (!lookup("location", "$fu")) {
                        sl_send_reply(404, "User Not Found");
                        exit;
                    }
                    route(OUTBOUND_CALL);
                }
            }
            
            # --- Inbound call routing (PSTN -> PBX-Core) ---
            route[INBOUND_CALL] {
                xlog("L_INFO", "Inbound call: $fu -> $rU\\n");
                
                # Build request body for PBX-Core
                $var(request_body) = "{" +
                    "\\"callId\\":\\"" + $ci + "\\"," +
                    "\\"from\\":\\"" + $fU + "\\"," +
                    "\\"to\\":\\"" + $rU + "\\"," +
                    "\\"tenantId\\":\\"" + TENANT_ID + "\\"," +
                    "\\"fromDisplay\\":\\"" + $fn + "\\"," +
                    "\\"sourceIp\\":\\"" + $si + "\\"," +
                    "\\"isWebRtc\\":" + $var(is_webrtc) +
                "}";
                
                # Async HTTP to PBX-Core for routing decision
                http_async_query(
                    PBX_CORE_URL "/v1/calls/ingress",
                    $var(request_body),
                    "PBX_REPLY"
                );
                exit;
            }
            
            # --- PBX-Core reply handler ---
            route[PBX_REPLY] {
                if (!$http_ok || $http_rs != 200 || $http_rb == "") {
                    xlog("L_ERR", "PBX-Core error: $http_rs\\n");
                    sl_send_reply(480, "Temporarily Unavailable");
                    exit;
                }
                
                # Parse JSON response
                jansson_get("action", $http_rb, "$var(action)");
                jansson_get("target", $http_rb, "$var(target)");
                jansson_get("ivrFlow", $http_rb, "$var(ivr_flow)");
                jansson_get("queueId", $http_rb, "$var(queue_id)");
                
                # Handle different actions
                if ($var(action) == "reject") {
                    jansson_get("reason", $http_rb, "$var(reason)");
                    sl_send_reply(603, $var(reason));
                    exit;
                }
                
                if ($var(action) == "ivr") {
                    # Route to IVR (FreeSWITCH)
                    append_hf("X-IVR-Flow: " + $var(ivr_flow) + "\\r\\n");
                    $du = "sip:ivr@freeswitch:5080";
                    route(RELAY);
                    exit;
                }
                
                if ($var(action) == "queue") {
                    # Route to ACD queue
                    append_hf("X-Queue-Id: " + $var(queue_id) + "\\r\\n");
                    $du = "sip:queue@freeswitch:5080";
                    route(RELAY);
                    exit;
                }
                
                if ($var(action) == "agent") {
                    # Direct to agent - lookup and relay
                    if ($var(target) != "") {
                        $ru = "sip:" + $var(target) + "@" + TENANT_REALM;
                        if (!lookup("location")) {
                            sl_send_reply(480, "Agent Unavailable");
                            exit;
                        }
                        route(RELAY);
                        exit;
                    }
                }
                
                if ($var(action) == "transfer") {
                    # External transfer
                    $du = $var(target);
                    route(RELAY);
                    exit;
                }
                
                # Default: try dispatcher (failover trunks)
                if (ds_select_dst("1", "4")) {
                    route(RELAY);
                    exit;
                }
                
                sl_send_reply(500, "No Route");
                exit;
            }
            
            # --- Outbound call routing (Agent -> PSTN) ---
            route[OUTBOUND_CALL] {
                xlog("L_INFO", "Outbound call: $fu -> $rU\\n");
                
                # Determine if PSTN destination
                if ($rU =~ "^\\\\+?[0-9]{10,15}$") {
                    route(PSTN_ROUTING);
                    exit;
                }
                
                # Internal call to another agent
                if (!lookup("location", "$ru")) {
                    sl_send_reply(404, "User Not Found");
                    exit;
                }
                
                route(RELAY);
            }
            
            # --- PSTN trunk routing ---
            route[PSTN_ROUTING] {
                # Select trunk based on prefix rules
                # Uses dispatcher for load balancing/failover
                if (!ds_select_dst("1", "4")) {
                    sl_send_reply(503, "No Trunks Available");
                    exit;
                }
                
                # UAC credentials for trunk auth
                uac_replace_from("", "sip:" + $rU + "@" + $dd);
                
                # Add P-Asserted-Identity if configured
                if ($fU =~ "^\\\\+?[0-9]+$") {
                    append_hf("P-Asserted-Identity: <sip:" + $fU + "@" + TENANT_REALM + ">\\r\\n");
                }
                
                route(RELAY);
            }
            
            # --- Message relay ---
            route[RELAY] {
                # RTPEngine for media handling
                if (isflagset(8)) {
                    rtpengine_manage("replace-origin replace-session-connection ICE=force DTLS=passive");
                } else if (isflagset(5)) {
                    rtpengine_manage("replace-origin replace-session-connection");
                }
                
                # Enable failure route
                t_on_failure("MANAGE_FAILURE");
                
                # Relay request
                if (!t_relay()) {
                    sl_reply_error();
                }
                exit;
            }
            
            # --- Within-dialog requests ---
            route[WITHINDLG] {
                if (!has_totag()) return;
                
                if (loose_route()) {
                    # Sequential request within dialog
                    if (is_method("BYE")) {
                        # Kafka event for call end
                        $var(bye_event) = "{" +
                            "\\"tenantId\\":\\"" + TENANT_ID + "\\"," +
                            "\\"callId\\":\\"" + $ci + "\\"," +
                            "\\"eventType\\":\\"BYE\\"" +
                        "}";
                        kafka_send(KAFKA_CALL_TOPIC, $ci, $var(bye_event));
                        
                        rtpengine_delete();
                        setflag(4);
                    }
                    
                    if (is_method("ACK")) {
                        route(NATMANAGE);
                    }
                    
                    if (is_method("INVITE|UPDATE")) {
                        route(NATMANAGE);
                    }
                    
                    route(RELAY);
                    exit;
                }
                
                if (is_method("ACK")) {
                    if (t_check_trans()) {
                        route(RELAY);
                        exit;
                    }
                    exit;
                }
                
                sl_send_reply(404, "Not Here");
                exit;
            }
            
            # --- NAT management for media ---
            route[NATMANAGE] {
                if (isflagset(5)) {
                    if (is_request()) {
                        if (has_body("application/sdp")) {
                            if (isflagset(8)) {
                                rtpengine_manage("replace-origin replace-session-connection ICE=force DTLS=passive");
                            } else {
                                rtpengine_manage("replace-origin replace-session-connection");
                            }
                        }
                    }
                }
            }
            
            # --- REFER handling (call transfer) ---
            route[REFER] {
                if (!is_method("REFER")) return;
                
                # Allow transfers within dialog only
                if (!has_totag()) {
                    sl_send_reply(481, "Call Does Not Exist");
                    exit;
                }
                
                if (loose_route()) {
                    route(RELAY);
                }
                exit;
            }
            
            # --- Presence (SUBSCRIBE/NOTIFY) ---
            route[PRESENCE] {
                # Forward to presence server or handle locally
                if (is_method("SUBSCRIBE")) {
                    if ($hdr(Event) == "presence" || $hdr(Event) == "dialog") {
                        # Handle locally or forward
                        sl_send_reply(202, "Accepted");
                        exit;
                    }
                }
                
                if (is_method("NOTIFY")) {
                    route(RELAY);
                    exit;
                }
                
                sl_send_reply(501, "Not Implemented");
                exit;
            }
            
            # --- MESSAGE handling ---
            route[MESSAGE] {
                # Could forward to a messaging service
                sl_send_reply(202, "Accepted");
                exit;
            }
            
            """;
    }
    
    private String buildEventRoutes(TelecomStackConfig config) {
        return """
            # ============================================================
            # EVENT ROUTES
            # ============================================================
            
            # --- Dialog state callback (Lua/KEMI style) ---
            event_route[dialog:start] {
                xlog("L_INFO", "Dialog started: $ci\\n");
                
                $var(start_event) = "{" +
                    "\\"tenantId\\":\\"" + TENANT_ID + "\\"," +
                    "\\"callId\\":\\"" + $ci + "\\"," +
                    "\\"from\\":\\"" + $fu + "\\"," +
                    "\\"to\\":\\"" + $ru + "\\"," +
                    "\\"eventType\\":\\"CALL_START\\"" +
                "}";
                kafka_send(KAFKA_CALL_TOPIC, $ci, $var(start_event));
            }
            
            event_route[dialog:end] {
                xlog("L_INFO", "Dialog ended: $ci (duration: $DLG_lifetime)\\n");
                
                $var(end_event) = "{" +
                    "\\"tenantId\\":\\"" + TENANT_ID + "\\"," +
                    "\\"callId\\":\\"" + $ci + "\\"," +
                    "\\"duration\\":" + $DLG_lifetime + "," +
                    "\\"eventType\\":\\"CALL_END\\"" +
                "}";
                kafka_send(KAFKA_CALL_TOPIC, $ci, $var(end_event));
            }
            
            # --- WebSocket events ---
            event_route[xhttp:request] {
                # Handle WebSocket upgrade
                if ($hdr(Upgrade) =~ "websocket" && $hdr(Connection) =~ "Upgrade") {
                    xlog("L_INFO", "WebSocket upgrade from $si\\n");
                    
                    if (ws_handle_handshake()) {
                        exit;
                    }
                }
                
                # Health check endpoint
                if ($hu == "/health") {
                    xhttp_reply(200, "OK", "text/plain", "healthy");
                    exit;
                }
                
                xhttp_reply(404, "Not Found", "text/plain", "Not Found");
                exit;
            }
            
            event_route[websocket:closed] {
                xlog("L_INFO", "WebSocket closed: $si:$sp\\n");
            }
            
            """;
    }
    
    private String buildFailureRoutes() {
        return """
            # ============================================================
            # FAILURE AND REPLY ROUTES
            # ============================================================
            
            failure_route[MANAGE_FAILURE] {
                xlog("L_WARN", "Failure: $T_reply_code for $rm $ru\\n");
                
                # Cleanup RTPEngine on final failure
                if (t_is_canceled()) {
                    rtpengine_delete();
                    exit;
                }
                
                # Try next destination in dispatcher set
                if (t_check_status("5[0-9][0-9]|6[0-9][0-9]")) {
                    if (ds_next_dst()) {
                        xlog("L_INFO", "Trying next destination\\n");
                        t_on_failure("MANAGE_FAILURE");
                        route(RELAY);
                        exit;
                    }
                }
                
                # NAT issues - try again with different RTP settings
                if (t_check_status("408|487")) {
                    rtpengine_delete();
                }
            }
            
            onreply_route {
                # Handle 1xx/2xx replies for RTPEngine
                if (has_body("application/sdp")) {
                    if (isflagset(8)) {
                        rtpengine_manage("replace-origin replace-session-connection ICE=force DTLS=passive");
                    } else if (isflagset(5)) {
                        rtpengine_manage("replace-origin replace-session-connection");
                    }
                }
                
                # Fix NATed contact in replies
                if (isflagset(5)) {
                    fix_nated_contact();
                }
            }
            
            # End of Kamailio configuration
            """;
    }
}
