package com.dalai.llama.preprod.dto;

/** Full cinematography taxonomy for one shot -- nested here rather than flattened onto {@link
 * ShotView} so the API stays legible; the underlying {@code Shot} entity stores these as flat
 * {@code cine_*} columns. */
public record CinematographyView(
        String cameraBody,
        String sensor,
        String captureFormat,
        String recordingCharacteristics,
        String positionHeight,
        String positionDistance,
        String positionLateral,
        String positionElevation,
        String positionOrientation,
        String lensFocalLength,
        String lensType,
        String lensOpticalFormat,
        String lensDistortion,
        String lensCompression,
        String lensCharacter,
        String framing,
        String subjectPlacement,
        String headroom,
        String leadRoom,
        String visualBalance,
        String focusTarget,
        String focusDistance,
        String depthOfField,
        String rackFocus,
        String focusBehaviour,
        String movementType,
        String movementTrajectory,
        String movementSpeed,
        String movementAcceleration,
        String movementRotation,
        String movementSubjectRelationship,
        String support,
        String aperture,
        String iso,
        String shutter,
        String ndFilter,
        String dynamicRange,
        String shutterAngle,
        String motionBlur,
        String slowMotion,
        String filtrationDiffusion,
        String filtrationNd,
        String filtrationPolarizer,
        String filtrationSpecialty,
        String contrast,
        String colorResponse,
        String grain,
        String halation,
        String bloom,
        String sharpness,
        String flare
) {
}
