package com.dalai.llama.creator.domain;

public enum PromptTemplateType {
    TREND_REFRESH,
    TREND_PREDICT,
    TREND_INSIGHT,
    AUDIENCE_SUGGEST,
    IDEA_GENERATE,
    STORY_SCRIPT_GENERATE,
    SCRIPT_GENERATE,
    SHOT_PRODUCTION_PLAN_GENERATE,
    STORYBOARD_TAG_GENERATE,
    LIGHTING_BUILD_SHEET_TAG_GENERATE,
    CAMERA_PLAN_SHEET_TAG_GENERATE,
    SHOT_JSON_EDIT,
    STORYBOARD_GENERATE,
    SCENE_REGENERATE,
    SHORTS_GENERATE,
    SHORTS_VIDEO_UNDERSTANDING,
    EXPORT_SUMMARY,
    CAST_FACE_REFERENCE_PROMPT,
    SCENE_PROMPT_COMPRESS,
    PHONEME_PRONUNCIATION_GUIDE
}
