INSERT INTO creator_ai_providers (
    id,
    code,
    display_name,
    description,
    provider_type,
    default_model,
    api_base_url,
    credential_env_key,
    sort_order,
    active,
    visible,
    default_provider,
    capabilities,
    metadata
) VALUES (
    gen_random_uuid(),
    'gemini',
    'Google Gemini',
    'Google Gemini Generative Language API provider for creator generation.',
    'LLM',
    'gemini-2.5-flash',
    'https://generativelanguage.googleapis.com/v1beta',
    'GEMINI_API_KEY',
    20,
    true,
    true,
    false,
    '{"textGeneration": true, "jsonOutput": true, "usageTokens": true}'::jsonb,
    '{"billingCurrency": "INR"}'::jsonb
)
ON CONFLICT (code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    provider_type = EXCLUDED.provider_type,
    default_model = EXCLUDED.default_model,
    api_base_url = EXCLUDED.api_base_url,
    credential_env_key = EXCLUDED.credential_env_key,
    sort_order = EXCLUDED.sort_order,
    active = EXCLUDED.active,
    visible = EXCLUDED.visible,
    default_provider = EXCLUDED.default_provider,
    capabilities = EXCLUDED.capabilities,
    metadata = EXCLUDED.metadata,
    updated_at = now();
