COMMENT ON TABLE creator_platforms IS 'Master data for Creator target platforms and ingestion signal sources. Target platforms are user-selectable publishing destinations; signal sources are hidden data collection origins.';
COMMENT ON COLUMN creator_platforms.id IS 'Primary key for the platform master record.';
COMMENT ON COLUMN creator_platforms.code IS 'Stable machine code used by APIs, jobs, prompts, and UI selections, for example instagram_reels.';
COMMENT ON COLUMN creator_platforms.display_name IS 'Human-readable platform label shown in UI.';
COMMENT ON COLUMN creator_platforms.status IS 'Legacy lifecycle status string kept for compatibility with early seed data.';
COMMENT ON COLUMN creator_platforms.metadata IS 'Extra platform configuration that does not need first-class columns yet.';
COMMENT ON COLUMN creator_platforms.created_at IS 'Timestamp when the platform record was created.';
COMMENT ON COLUMN creator_platforms.updated_at IS 'Timestamp when the platform record was last updated.';
COMMENT ON COLUMN creator_platforms.description IS 'Short product description for UI/admin display.';
COMMENT ON COLUMN creator_platforms.icon_key IS 'Frontend icon key, usually mapped to a lucide icon.';
COMMENT ON COLUMN creator_platforms.sort_order IS 'Display ordering for platform pickers.';
COMMENT ON COLUMN creator_platforms.active IS 'Whether the platform can be used by scheduler/API logic.';
COMMENT ON COLUMN creator_platforms.visible IS 'Whether the platform appears in end-user UI.';
COMMENT ON COLUMN creator_platforms.target_platform IS 'True when creators can optimize content for this publishing platform.';
COMMENT ON COLUMN creator_platforms.signal_source IS 'True when this row represents a trend data source rather than a publishing destination.';
COMMENT ON COLUMN creator_platforms.short_form IS 'True when the platform is short-form vertical video focused.';
COMMENT ON COLUMN creator_platforms.prompt_context IS 'Prompt guidance specific to this platform.';

COMMENT ON TABLE creator_categories IS 'Master data for Creator trend topic categories shown as UI filters and used by ingestion/prompt logic.';
COMMENT ON COLUMN creator_categories.id IS 'Primary key for the category master record.';
COMMENT ON COLUMN creator_categories.code IS 'Stable machine category code used by APIs, jobs, prompts, and filters, for example fitness.';
COMMENT ON COLUMN creator_categories.display_name IS 'Human-readable category label shown in UI.';
COMMENT ON COLUMN creator_categories.status IS 'Legacy lifecycle status string kept for compatibility with early seed data.';
COMMENT ON COLUMN creator_categories.metadata IS 'Extra category configuration that does not need first-class columns yet.';
COMMENT ON COLUMN creator_categories.created_at IS 'Timestamp when the category record was created.';
COMMENT ON COLUMN creator_categories.updated_at IS 'Timestamp when the category record was last updated.';
COMMENT ON COLUMN creator_categories.description IS 'Short category description for UI/admin display.';
COMMENT ON COLUMN creator_categories.icon_key IS 'Frontend icon key, usually mapped to a lucide icon.';
COMMENT ON COLUMN creator_categories.sort_order IS 'Display ordering for category pickers.';
COMMENT ON COLUMN creator_categories.active IS 'Whether the category can be used by scheduler/API logic.';
COMMENT ON COLUMN creator_categories.visible IS 'Whether the category appears in end-user UI.';
COMMENT ON COLUMN creator_categories.prompt_context IS 'Prompt guidance specific to this category.';

COMMENT ON TABLE creator_category_keywords IS 'Scheduler query and classification mappings for category-specific no-key trend ingestion sources.';
COMMENT ON COLUMN creator_category_keywords.id IS 'Primary key for the category keyword mapping.';
COMMENT ON COLUMN creator_category_keywords.category_id IS 'Category that owns this source keyword mapping.';
COMMENT ON COLUMN creator_category_keywords.source_type IS 'Ingestion source type, for example google_trends, reddit, or youtube_public_pages.';
COMMENT ON COLUMN creator_category_keywords.locale IS 'Locale/country-language context for the terms, for example en-IN.';
COMMENT ON COLUMN creator_category_keywords.include_terms IS 'JSON array of source search terms or community hints to include.';
COMMENT ON COLUMN creator_category_keywords.exclude_terms IS 'JSON array of unsafe, noisy, or irrelevant terms to exclude.';
COMMENT ON COLUMN creator_category_keywords.weight IS 'Relative confidence/priority used by the scheduler when collecting or ranking signals.';
COMMENT ON COLUMN creator_category_keywords.active IS 'Whether the scheduler should use this mapping.';
COMMENT ON COLUMN creator_category_keywords.created_at IS 'Timestamp when the keyword mapping was created.';
COMMENT ON COLUMN creator_category_keywords.updated_at IS 'Timestamp when the keyword mapping was last updated.';

COMMENT ON TABLE creator_trend_combinations IS 'Valid matrix of target platform and category selections supported by Creator trend prediction.';
COMMENT ON COLUMN creator_trend_combinations.id IS 'Primary key for the platform/category combination.';
COMMENT ON COLUMN creator_trend_combinations.platform_code IS 'Target publishing platform code, for example instagram_reels.';
COMMENT ON COLUMN creator_trend_combinations.category_code IS 'Topic category code, for example fitness.';
COMMENT ON COLUMN creator_trend_combinations.enabled IS 'Whether users can select this platform/category pair.';
COMMENT ON COLUMN creator_trend_combinations.free_source_policy IS 'JSON policy describing no-key sources and scheduler rules for this combination.';
COMMENT ON COLUMN creator_trend_combinations.metadata IS 'Extra combination configuration that does not need first-class columns yet.';
COMMENT ON COLUMN creator_trend_combinations.created_at IS 'Timestamp when the combination was created.';
COMMENT ON COLUMN creator_trend_combinations.updated_at IS 'Timestamp when the combination was last updated.';

COMMENT ON TABLE creator_projects IS 'Current and historical Creator planning memory for a user draft or generation flow.';
COMMENT ON COLUMN creator_projects.id IS 'Primary key for the creator project.';
COMMENT ON COLUMN creator_projects.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_projects.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_projects.status IS 'Project lifecycle state such as DRAFT, LOCKED, GENERATED, or ARCHIVED.';
COMMENT ON COLUMN creator_projects.selected_platform_code IS 'Currently selected target platform code.';
COMMENT ON COLUMN creator_projects.selected_category_code IS 'Currently selected trend category code.';
COMMENT ON COLUMN creator_projects.timeframe IS 'Trend analysis window selected by the user.';
COMMENT ON COLUMN creator_projects.country_code IS 'Country or market context for trend collection and prompts.';
COMMENT ON COLUMN creator_projects.duration_seconds IS 'Selected short duration in seconds, normally 30, 45, or 60.';
COMMENT ON COLUMN creator_projects.selected_trend_id IS 'Trend selected by the user for idea/storyboard generation.';
COMMENT ON COLUMN creator_projects.selected_audience_id IS 'Confirmed or active target audience record.';
COMMENT ON COLUMN creator_projects.selected_profile_id IS 'Confirmed or active creator/cast profile record.';
COMMENT ON COLUMN creator_projects.selected_idea_id IS 'Locked or currently selected idea record.';
COMMENT ON COLUMN creator_projects.selected_storyboard_id IS 'Current generated storyboard record.';
COMMENT ON COLUMN creator_projects.preferences IS 'User-editable project preferences and UI state.';
COMMENT ON COLUMN creator_projects.memory_snapshot IS 'Persisted AI memory snapshot used to render prompts reproducibly.';
COMMENT ON COLUMN creator_projects.created_at IS 'Timestamp when the project was created.';
COMMENT ON COLUMN creator_projects.updated_at IS 'Timestamp when the project was last updated.';

COMMENT ON TABLE creator_trend_dumps IS 'Raw 30-minute trend collection batches before normalization and AI prediction.';
COMMENT ON COLUMN creator_trend_dumps.id IS 'Primary key for the raw trend dump.';
COMMENT ON COLUMN creator_trend_dumps.platform_code IS 'Target platform context the dump was collected for.';
COMMENT ON COLUMN creator_trend_dumps.category_code IS 'Category context the dump was collected for.';
COMMENT ON COLUMN creator_trend_dumps.country_code IS 'Country or market context for the dump.';
COMMENT ON COLUMN creator_trend_dumps.window_started_at IS 'Start timestamp of the collection window.';
COMMENT ON COLUMN creator_trend_dumps.window_ended_at IS 'End timestamp of the collection window.';
COMMENT ON COLUMN creator_trend_dumps.source_name IS 'No-key source that produced the dump, for example reddit or google_trends.';
COMMENT ON COLUMN creator_trend_dumps.source_url IS 'Optional URL used for collection or traceability.';
COMMENT ON COLUMN creator_trend_dumps.raw_payload IS 'Unnormalized source payload preserved for audit and later analysis.';
COMMENT ON COLUMN creator_trend_dumps.status IS 'Collection status such as COLLECTED, NORMALIZED, FAILED, or IGNORED.';
COMMENT ON COLUMN creator_trend_dumps.created_at IS 'Timestamp when the dump was stored.';

COMMENT ON TABLE creator_trends IS 'Normalized and ranked trend records shown to users and used for idea/storyboard generation.';
COMMENT ON COLUMN creator_trends.id IS 'Primary key for the normalized trend.';
COMMENT ON COLUMN creator_trends.trend_dump_id IS 'Raw dump that produced or contributed to this trend.';
COMMENT ON COLUMN creator_trends.platform_code IS 'Target publishing platform this trend is predicted for.';
COMMENT ON COLUMN creator_trends.category_code IS 'Primary category code for this trend.';
COMMENT ON COLUMN creator_trends.country_code IS 'Country or market context for this trend.';
COMMENT ON COLUMN creator_trends.title IS 'Short user-facing trend title.';
COMMENT ON COLUMN creator_trends.summary IS 'Trend explanation shown in UI and used in prompts.';
COMMENT ON COLUMN creator_trends.source_name IS 'Primary source signal for traceability.';
COMMENT ON COLUMN creator_trends.source_url IS 'Optional source URL for traceability.';
COMMENT ON COLUMN creator_trends.score IS 'Overall ranking score after normalization/prediction.';
COMMENT ON COLUMN creator_trends.velocity IS 'Momentum score indicating how quickly the signal is moving.';
COMMENT ON COLUMN creator_trends.tags IS 'JSON array of hashtags, phrases, or classifier tags.';
COMMENT ON COLUMN creator_trends.source_payload IS 'Normalized source details kept for analysis and prompt grounding.';
COMMENT ON COLUMN creator_trends.prediction_payload IS 'AI prediction details and reasoning for this trend.';
COMMENT ON COLUMN creator_trends.status IS 'Trend lifecycle state such as ACTIVE, STALE, HIDDEN, or ARCHIVED.';
COMMENT ON COLUMN creator_trends.first_seen_at IS 'First time this trend was observed.';
COMMENT ON COLUMN creator_trends.last_seen_at IS 'Most recent time this trend was observed.';
COMMENT ON COLUMN creator_trends.created_at IS 'Timestamp when the trend record was created.';

COMMENT ON TABLE creator_trend_category_map IS 'Many-to-many classification table allowing one trend to belong to multiple categories.';
COMMENT ON COLUMN creator_trend_category_map.trend_id IS 'Trend being mapped to a category.';
COMMENT ON COLUMN creator_trend_category_map.category_id IS 'Category assigned to the trend.';
COMMENT ON COLUMN creator_trend_category_map.confidence_score IS 'Classifier confidence for this category assignment.';
COMMENT ON COLUMN creator_trend_category_map.mapped_by IS 'Mapping origin such as scheduler, ai, admin, or manual.';
COMMENT ON COLUMN creator_trend_category_map.created_at IS 'Timestamp when the category mapping was created.';

COMMENT ON TABLE creator_audiences IS 'Suggested or confirmed target audience records for a creator project.';
COMMENT ON COLUMN creator_audiences.id IS 'Primary key for the audience record.';
COMMENT ON COLUMN creator_audiences.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_audiences.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_audiences.project_id IS 'Project this audience belongs to.';
COMMENT ON COLUMN creator_audiences.title IS 'Human-readable audience segment title.';
COMMENT ON COLUMN creator_audiences.demographics IS 'JSON demographic details such as age, gender, geography, or income level.';
COMMENT ON COLUMN creator_audiences.interests IS 'JSON array of interests and affinities.';
COMMENT ON COLUMN creator_audiences.psychographics IS 'JSON motivation, pain-point, and behavior details.';
COMMENT ON COLUMN creator_audiences.content_preference IS 'Preferred tone or format for this audience.';
COMMENT ON COLUMN creator_audiences.ai_suggested IS 'True when generated by AI instead of manually created.';
COMMENT ON COLUMN creator_audiences.confirmed IS 'True when the user has locked/confirmed this audience for generation.';
COMMENT ON COLUMN creator_audiences.created_at IS 'Timestamp when the audience was created.';
COMMENT ON COLUMN creator_audiences.updated_at IS 'Timestamp when the audience was last updated.';

COMMENT ON TABLE creator_profiles IS 'Creator or cast profile records used to tailor ideas, scripts, and storyboard directions.';
COMMENT ON COLUMN creator_profiles.id IS 'Primary key for the creator/cast profile.';
COMMENT ON COLUMN creator_profiles.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_profiles.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_profiles.project_id IS 'Optional project this profile was created in.';
COMMENT ON COLUMN creator_profiles.display_name IS 'Actor, creator, or cast member display name.';
COMMENT ON COLUMN creator_profiles.role_in_short IS 'Role the person plays in the short, for example main actor.';
COMMENT ON COLUMN creator_profiles.attributes IS 'JSON profile details such as age, gender, vibe, comfort, style, and skill level.';
COMMENT ON COLUMN creator_profiles.confirmed IS 'True when the user has locked/confirmed this cast profile for generation.';
COMMENT ON COLUMN creator_profiles.created_at IS 'Timestamp when the profile was created.';
COMMENT ON COLUMN creator_profiles.updated_at IS 'Timestamp when the profile was last updated.';

COMMENT ON TABLE creator_ideas IS 'Manual or AI-generated short concept ideas associated with trends, audience, and cast.';
COMMENT ON COLUMN creator_ideas.id IS 'Primary key for the idea record.';
COMMENT ON COLUMN creator_ideas.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_ideas.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_ideas.project_id IS 'Project this idea belongs to.';
COMMENT ON COLUMN creator_ideas.trend_id IS 'Optional trend that inspired this idea.';
COMMENT ON COLUMN creator_ideas.source IS 'Idea source such as MANUAL, AI_FROM_TREND, or AI_FROM_SCRIPT.';
COMMENT ON COLUMN creator_ideas.title IS 'Short idea title.';
COMMENT ON COLUMN creator_ideas.summary IS 'Short idea summary shown in UI.';
COMMENT ON COLUMN creator_ideas.script IS 'Creator-provided or AI-generated script text.';
COMMENT ON COLUMN creator_ideas.scenes IS 'JSON scene-by-scene draft before storyboard generation.';
COMMENT ON COLUMN creator_ideas.duration_seconds IS 'Intended short duration in seconds.';
COMMENT ON COLUMN creator_ideas.status IS 'Idea lifecycle state such as DRAFT, SELECTED, LOCKED, or ARCHIVED.';
COMMENT ON COLUMN creator_ideas.saved IS 'True when user saved this idea for later.';
COMMENT ON COLUMN creator_ideas.generation_job_id IS 'Async generation job that produced this idea, when applicable.';
COMMENT ON COLUMN creator_ideas.prompt_run_id IS 'Prompt run that produced this idea, when applicable.';
COMMENT ON COLUMN creator_ideas.created_at IS 'Timestamp when the idea was created.';
COMMENT ON COLUMN creator_ideas.updated_at IS 'Timestamp when the idea was last updated.';

COMMENT ON TABLE creator_storyboards IS 'Storyboard master record generated from a locked idea, trend, audience, cast, and duration.';
COMMENT ON COLUMN creator_storyboards.id IS 'Primary key for the storyboard.';
COMMENT ON COLUMN creator_storyboards.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_storyboards.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_storyboards.project_id IS 'Project this storyboard belongs to.';
COMMENT ON COLUMN creator_storyboards.idea_id IS 'Locked idea used to generate this storyboard.';
COMMENT ON COLUMN creator_storyboards.title IS 'Storyboard title.';
COMMENT ON COLUMN creator_storyboards.duration_seconds IS 'Total intended video duration in seconds.';
COMMENT ON COLUMN creator_storyboards.total_shots IS 'Number of storyboard shots/scenes.';
COMMENT ON COLUMN creator_storyboards.pacing_style IS 'High-level pacing direction for the short.';
COMMENT ON COLUMN creator_storyboards.emotional_arc IS 'Emotional progression across the short.';
COMMENT ON COLUMN creator_storyboards.hook_strategy IS 'Opening hook strategy used to retain viewers.';
COMMENT ON COLUMN creator_storyboards.creator_fit_reasoning IS 'Why the storyboard fits the selected creator/cast.';
COMMENT ON COLUMN creator_storyboards.audience_fit_reasoning IS 'Why the storyboard fits the selected target audience.';
COMMENT ON COLUMN creator_storyboards.overall_execution_difficulty IS 'Overall execution difficulty label.';
COMMENT ON COLUMN creator_storyboards.status IS 'Storyboard lifecycle state such as GENERATED, SAVED, EXPORTED, or ARCHIVED.';
COMMENT ON COLUMN creator_storyboards.saved IS 'True when user saved this storyboard.';
COMMENT ON COLUMN creator_storyboards.metadata IS 'Extra storyboard details that do not need first-class columns yet.';
COMMENT ON COLUMN creator_storyboards.created_at IS 'Timestamp when the storyboard was created.';
COMMENT ON COLUMN creator_storyboards.updated_at IS 'Timestamp when the storyboard was last updated.';

COMMENT ON TABLE creator_storyboard_scenes IS 'Shot-by-shot director details and image prompt metadata for a storyboard.';
COMMENT ON COLUMN creator_storyboard_scenes.id IS 'Primary key for the storyboard scene.';
COMMENT ON COLUMN creator_storyboard_scenes.storyboard_id IS 'Storyboard this scene belongs to.';
COMMENT ON COLUMN creator_storyboard_scenes.image_asset_id IS 'Generated storyboard image asset for this shot.';
COMMENT ON COLUMN creator_storyboard_scenes.shot_number IS 'Shot order inside the storyboard.';
COMMENT ON COLUMN creator_storyboard_scenes.start_time IS 'Human-readable shot start time, for example 0:06.';
COMMENT ON COLUMN creator_storyboard_scenes.end_time IS 'Human-readable shot end time, for example 0:08.';
COMMENT ON COLUMN creator_storyboard_scenes.duration_seconds IS 'Shot duration in seconds.';
COMMENT ON COLUMN creator_storyboard_scenes.title IS 'Short shot title.';
COMMENT ON COLUMN creator_storyboard_scenes.purpose IS 'Narrative or retention purpose of the shot.';
COMMENT ON COLUMN creator_storyboard_scenes.shot_type IS 'Shot type such as Close Up, Medium Shot, or Wide Shot.';
COMMENT ON COLUMN creator_storyboard_scenes.camera_angle IS 'Camera angle or framing instruction.';
COMMENT ON COLUMN creator_storyboard_scenes.camera_movement IS 'Camera movement instruction.';
COMMENT ON COLUMN creator_storyboard_scenes.lens_suggestion IS 'Phone/lens suggestion for the creator.';
COMMENT ON COLUMN creator_storyboard_scenes.fps IS 'Recommended capture frame rate.';
COMMENT ON COLUMN creator_storyboard_scenes.composition IS 'Composition and subject placement direction.';
COMMENT ON COLUMN creator_storyboard_scenes.expression IS 'JSON map of character expressions.';
COMMENT ON COLUMN creator_storyboard_scenes.emotion IS 'JSON array of emotional beats in the shot.';
COMMENT ON COLUMN creator_storyboard_scenes.body_language IS 'JSON map of character body language direction.';
COMMENT ON COLUMN creator_storyboard_scenes.lighting IS 'Lighting direction.';
COMMENT ON COLUMN creator_storyboard_scenes.environment IS 'Location or set direction.';
COMMENT ON COLUMN creator_storyboard_scenes.action IS 'Primary on-screen action.';
COMMENT ON COLUMN creator_storyboard_scenes.voice_over IS 'Voiceover line or note for the shot.';
COMMENT ON COLUMN creator_storyboard_scenes.dialogue IS 'JSON map of speaker dialogue.';
COMMENT ON COLUMN creator_storyboard_scenes.text_overlay IS 'On-screen text overlay.';
COMMENT ON COLUMN creator_storyboard_scenes.transition IS 'Transition into or out of the shot.';
COMMENT ON COLUMN creator_storyboard_scenes.sound_design IS 'JSON array of music, ambience, and sound effect notes.';
COMMENT ON COLUMN creator_storyboard_scenes.editing_notes IS 'JSON array of editing instructions.';
COMMENT ON COLUMN creator_storyboard_scenes.retention_goal IS 'Viewer retention goal for this shot.';
COMMENT ON COLUMN creator_storyboard_scenes.creator_direction IS 'JSON map of actor/creator direction.';
COMMENT ON COLUMN creator_storyboard_scenes.subtitle_position IS 'Recommended subtitle placement.';
COMMENT ON COLUMN creator_storyboard_scenes.mobile_focus_area IS 'Primary mobile-safe visual focus area.';
COMMENT ON COLUMN creator_storyboard_scenes.safe_zone_notes IS 'Safe zone notes for platform UI overlays.';
COMMENT ON COLUMN creator_storyboard_scenes.execution_difficulty IS 'JSON difficulty and requirements object.';
COMMENT ON COLUMN creator_storyboard_scenes.cinematic_execution IS 'JSON capture and editing execution details.';
COMMENT ON COLUMN creator_storyboard_scenes.rookie_friendly_guide IS 'JSON beginner-friendly shooting guidance.';
COMMENT ON COLUMN creator_storyboard_scenes.sketch_prompt IS 'Prompt used to generate the storyboard sketch/image.';
COMMENT ON COLUMN creator_storyboard_scenes.metadata IS 'Extra scene details that do not need first-class columns yet.';
COMMENT ON COLUMN creator_storyboard_scenes.created_at IS 'Timestamp when the scene was created.';
COMMENT ON COLUMN creator_storyboard_scenes.updated_at IS 'Timestamp when the scene was last updated.';

COMMENT ON TABLE creator_assets IS 'Metadata for generated images, exports, and other files stored in S3/MinIO.';
COMMENT ON COLUMN creator_assets.id IS 'Primary key for the asset metadata record.';
COMMENT ON COLUMN creator_assets.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_assets.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_assets.project_id IS 'Project associated with this asset, when applicable.';
COMMENT ON COLUMN creator_assets.storyboard_id IS 'Storyboard associated with this asset, when applicable.';
COMMENT ON COLUMN creator_assets.asset_type IS 'Asset kind such as STORYBOARD_IMAGE or EXPORT_PACKAGE.';
COMMENT ON COLUMN creator_assets.bucket IS 'S3/MinIO bucket containing the object.';
COMMENT ON COLUMN creator_assets.object_key IS 'S3/MinIO object key.';
COMMENT ON COLUMN creator_assets.content_type IS 'MIME type of the stored object.';
COMMENT ON COLUMN creator_assets.size_bytes IS 'Object size in bytes.';
COMMENT ON COLUMN creator_assets.public_url IS 'Public or signed URL when available.';
COMMENT ON COLUMN creator_assets.metadata IS 'Extra asset metadata that does not need first-class columns yet.';
COMMENT ON COLUMN creator_assets.created_at IS 'Timestamp when the asset metadata was created.';

COMMENT ON TABLE creator_generation_jobs IS 'Persistent async job records for paid and AI CTA flows.';
COMMENT ON COLUMN creator_generation_jobs.id IS 'Primary key for the generation job.';
COMMENT ON COLUMN creator_generation_jobs.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_generation_jobs.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_generation_jobs.project_id IS 'Project associated with this job.';
COMMENT ON COLUMN creator_generation_jobs.job_type IS 'Job type such as TREND_REFRESH, IDEA_GENERATE, or STORYBOARD_GENERATE.';
COMMENT ON COLUMN creator_generation_jobs.status IS 'Job status such as PENDING, RUNNING, COMPLETED, FAILED, or CANCELLED.';
COMMENT ON COLUMN creator_generation_jobs.progress IS 'Approximate job progress percentage.';
COMMENT ON COLUMN creator_generation_jobs.redis_key IS 'Redis key used for short-running progress updates.';
COMMENT ON COLUMN creator_generation_jobs.kafka_topic IS 'Kafka topic the job was published to.';
COMMENT ON COLUMN creator_generation_jobs.input_payload IS 'JSON input payload captured when the job was created.';
COMMENT ON COLUMN creator_generation_jobs.output_payload IS 'JSON output payload or resource references after completion.';
COMMENT ON COLUMN creator_generation_jobs.error_message IS 'Failure reason when status is FAILED.';
COMMENT ON COLUMN creator_generation_jobs.created_at IS 'Timestamp when the job was created.';
COMMENT ON COLUMN creator_generation_jobs.started_at IS 'Timestamp when the job started running.';
COMMENT ON COLUMN creator_generation_jobs.completed_at IS 'Timestamp when the job completed or failed.';

COMMENT ON TABLE creator_prompt_templates IS 'Versioned prompt templates used by Creator AI workflows.';
COMMENT ON COLUMN creator_prompt_templates.id IS 'Primary key for the prompt template.';
COMMENT ON COLUMN creator_prompt_templates.template_key IS 'Stable prompt type key, for example STORYBOARD_GENERATE.';
COMMENT ON COLUMN creator_prompt_templates.version IS 'Template version used for reproducibility.';
COMMENT ON COLUMN creator_prompt_templates.name IS 'Human-readable template name.';
COMMENT ON COLUMN creator_prompt_templates.template_body IS 'Prompt template text with placeholders.';
COMMENT ON COLUMN creator_prompt_templates.status IS 'Template lifecycle state such as ACTIVE or RETIRED.';
COMMENT ON COLUMN creator_prompt_templates.metadata IS 'Extra template metadata that does not need first-class columns yet.';
COMMENT ON COLUMN creator_prompt_templates.created_at IS 'Timestamp when the template was created.';
COMMENT ON COLUMN creator_prompt_templates.updated_at IS 'Timestamp when the template was last updated.';

COMMENT ON TABLE creator_prompt_runs IS 'Audit and memory records for every rendered AI prompt and provider response.';
COMMENT ON COLUMN creator_prompt_runs.id IS 'Primary key for the prompt run.';
COMMENT ON COLUMN creator_prompt_runs.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_prompt_runs.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_prompt_runs.project_id IS 'Project associated with this prompt run.';
COMMENT ON COLUMN creator_prompt_runs.job_id IS 'Generation job associated with this prompt run.';
COMMENT ON COLUMN creator_prompt_runs.prompt_template_id IS 'Template row used to render the prompt.';
COMMENT ON COLUMN creator_prompt_runs.prompt_template_key IS 'Prompt template key copied for audit stability.';
COMMENT ON COLUMN creator_prompt_runs.prompt_template_version IS 'Prompt template version copied for audit stability.';
COMMENT ON COLUMN creator_prompt_runs.rendered_prompt IS 'Full rendered prompt sent to the AI provider.';
COMMENT ON COLUMN creator_prompt_runs.input_snapshot IS 'JSON project memory/input snapshot used to render the prompt.';
COMMENT ON COLUMN creator_prompt_runs.provider IS 'AI provider name such as mock, openai, or gemini.';
COMMENT ON COLUMN creator_prompt_runs.model IS 'Provider model identifier.';
COMMENT ON COLUMN creator_prompt_runs.output_payload IS 'Structured AI response or parsed output.';
COMMENT ON COLUMN creator_prompt_runs.status IS 'Prompt run status such as PENDING, COMPLETED, or FAILED.';
COMMENT ON COLUMN creator_prompt_runs.error_message IS 'Failure reason when status is FAILED.';
COMMENT ON COLUMN creator_prompt_runs.token_metadata IS 'Token usage metadata for future real AI providers.';
COMMENT ON COLUMN creator_prompt_runs.cost_metadata IS 'Cost metadata for future billing/reconciliation.';
COMMENT ON COLUMN creator_prompt_runs.created_at IS 'Timestamp when the prompt run was created.';
COMMENT ON COLUMN creator_prompt_runs.completed_at IS 'Timestamp when the prompt run completed or failed.';

COMMENT ON TABLE creator_activity_events IS 'Append-only product analytics and preview interaction events.';
COMMENT ON COLUMN creator_activity_events.id IS 'Primary key for the activity event.';
COMMENT ON COLUMN creator_activity_events.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_activity_events.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_activity_events.project_id IS 'Project associated with the activity event.';
COMMENT ON COLUMN creator_activity_events.event_type IS 'Event name such as PREVIEW_LIKE, PREVIEW_SHARE, or CTA_CLICK.';
COMMENT ON COLUMN creator_activity_events.event_payload IS 'JSON event details for analytics.';
COMMENT ON COLUMN creator_activity_events.created_at IS 'Timestamp when the event was captured.';

COMMENT ON TABLE creator_saved_items IS 'Generic saved-item mapping for saved ideas, storyboards, trends, and future item types.';
COMMENT ON COLUMN creator_saved_items.id IS 'Primary key for the saved item mapping.';
COMMENT ON COLUMN creator_saved_items.tenant_id IS 'Tenant or organization identifier from auth/platform context.';
COMMENT ON COLUMN creator_saved_items.user_id IS 'Creator user identifier from auth context.';
COMMENT ON COLUMN creator_saved_items.item_type IS 'Saved object type such as IDEA, STORYBOARD, or TREND.';
COMMENT ON COLUMN creator_saved_items.item_id IS 'Primary key of the saved object.';
COMMENT ON COLUMN creator_saved_items.metadata IS 'Extra saved-item metadata.';
COMMENT ON COLUMN creator_saved_items.created_at IS 'Timestamp when the item was saved.';
