CREATE TABLE creator_storyboard_chat_messages
(
    id                      UUID PRIMARY KEY,

    workspace_id            UUID NOT NULL,

    -- USER, ASSISTANT, SYSTEM
    role                    VARCHAR(20) NOT NULL,

    message                 TEXT NOT NULL,

    assistant_response      TEXT,

    -- AI's understanding of the request (target shots, intent type, etc).
    intent_payload          JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Operations generated by the AI for this turn.
    operations              JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Shot numbers this turn touched.
    affected_shots          JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Workspace version this turn produced, if any (null for Q&A-only turns
    -- that didn't change anything).
    applied_version         INTEGER,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_storyboard_chat_workspace
        FOREIGN KEY (workspace_id)
            REFERENCES creator_storyboard_workspaces(id)
            ON DELETE CASCADE
);

CREATE INDEX idx_storyboard_chat_workspace
    ON creator_storyboard_chat_messages (workspace_id);

CREATE INDEX idx_storyboard_chat_created
    ON creator_storyboard_chat_messages (workspace_id, created_at);

CREATE INDEX idx_storyboard_chat_role
    ON creator_storyboard_chat_messages (role);
