package com.dalai.llama.preprod.service;

import com.dalai.llama.preprod.domain.ShotListJobStatus;
import com.dalai.llama.preprod.domain.entity.ShotListJob;
import com.dalai.llama.preprod.dto.ShotListJobView;
import com.dalai.llama.preprod.kafka.ChatJobRequestedEvent;
import com.dalai.llama.preprod.kafka.ChatJobRequestedPublisher;
import com.dalai.llama.preprod.repository.ShotListJobRepository;
import com.dalai.llama.preprod.service.ShotListGenerationService.ShotListJobPreparation;
import com.dalai.llama.preprod.service.llmgateway.LlmGatewayChatRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.UUID;

/**
 * Owns the async shot-list-generation job lifecycle from the caller side. Steps: (1) build the
 * exact LLM request the sync path would have sent, (2) insert a local {@link ShotListJob} row in
 * PENDING with the shared idempotency key so the completed-event consumer can find it, (3)
 * publish {@link ChatJobRequestedEvent} to {@code llm.job.requested} for llm-gateway's worker to
 * pick up. The controller returns immediately with the created job's id; the terminal
 * SUCCEEDED/FAILED transition happens later inside
 * {@link com.dalai.llama.preprod.kafka.ChatJobCompletedConsumer}.
 *
 * <p>Idempotency: the local job row's {@code llm_job_idempotency_key} column has a UNIQUE index
 * (see V49), so a duplicate POST for the same project won't create two jobs; the existing job
 * is returned and re-queued (llm-gateway itself is idempotent on the same key too, so no second
 * Gemini call happens).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ShotListGenerationJobService {

    private final ShotListJobRepository shotListJobRepository;
    private final ShotListGenerationService shotListGenerationService;
    private final ChatJobRequestedPublisher chatJobRequestedPublisher;
    private final PlatformTransactionManager transactionManager;

    /**
     * Submits a new (or replays an existing not-yet-terminal) shot-list generation job. Returns
     * the view the controller responds with. If a prior job for this project already succeeded,
     * a fresh one is created -- generation is naturally re-entrant (see {@link
     * ShotListGenerationService#persistFromLlmResponse} which wipes and rewrites the shot rows).
     */
    @Transactional(propagation = Propagation.NOT_SUPPORTED)
    public ShotListJobView submit(UUID tenantId, UUID projectId) {
        return submit(tenantId, projectId, false);
    }

    /** {@code force} appends a nonce to the idempotency key so llm-gateway cannot replay its
     * cached completed response. Needed because the key covers the screenplay + script but NOT
     * the prompt template version -- after a template republish (e.g. the v11 screenplay-scenes
     * rewrite) the inputs are byte-identical, the key is identical, and the creator keeps getting
     * the answer generated by the OLD template with no way to escape it. This is a real, billed
     * LLM call every time, so it stays opt-in rather than becoming the default. */
    @Transactional(propagation = Propagation.NOT_SUPPORTED)
    public ShotListJobView submit(UUID tenantId, UUID projectId, boolean force) {
        TransactionTemplate transaction = new TransactionTemplate(transactionManager);
        PendingSubmission submission = transaction.execute(status -> prepareSubmission(tenantId, projectId, force));
        // A cached gateway result can return immediately. The PENDING row must be committed
        // before Kafka receives the request, otherwise the completion consumer sees the old
        // terminal status and discards the only completion event.
        try {
            chatJobRequestedPublisher.publish(submission.event());
        } catch (RuntimeException ex) {
            transaction.executeWithoutResult(status -> shotListJobRepository.findById(submission.job().getId())
                    .filter(job -> job.getStatus() == ShotListJobStatus.PENDING)
                    .ifPresent(job -> {
                        job.setStatus(ShotListJobStatus.FAILED);
                        job.setErrorMessage("Could not submit shot-list generation. Please retry. " + ex.getMessage());
                        job.setUpdatedAt(OffsetDateTime.now());
                        job.setCompletedAt(job.getUpdatedAt());
                        shotListJobRepository.save(job);
                    }));
            throw ex;
        }
        log.info("Submitted shot-list generation jobId={} projectId={} idempotencyKey={}",
                submission.job().getId(), projectId, submission.event().idempotencyKey());
        return ShotListJobView.from(submission.job());
    }

    private record PendingSubmission(ShotListJob job, ChatJobRequestedEvent event) {}

    private PendingSubmission prepareSubmission(UUID tenantId, UUID projectId, boolean force) {
        // Fail fast if the prerequisites (script, screenplay, scenes) aren't there -- surface a
        // clean 400 to the client synchronously rather than persisting a job that would only fail
        // on the worker side moments later. prepareJob throws PreProductionException
        // (badRequest/notFound) for each of those preconditions AND encodes the current
        // screenplay id + script updatedAt into the idempotency key so a regenerate after any
        // upstream edit doesn't replay llm-gateway's cached completed response.
        ShotListJobPreparation prep = shotListGenerationService.prepareJob(tenantId, projectId);
        LlmGatewayChatRequest request = prep.request();
        // A forced run gets a one-off key so both llm-gateway's llm_job cache and our own
        // shot_list_job row are fresh -- otherwise findByLlmJobIdempotencyKey would reuse the
        // terminal row and the gateway would replay its stored resultContent.
        String idempotencyKey = force
                ? prep.idempotencyKey() + "-force" + System.currentTimeMillis()
                : prep.idempotencyKey();
        ShotListJob job = shotListJobRepository.findByLlmJobIdempotencyKey(idempotencyKey)
                .map(existing -> resubmitIfTerminal(existing, tenantId))
                .orElseGet(() -> createPending(tenantId, projectId, idempotencyKey));

        return new PendingSubmission(job, new ChatJobRequestedEvent(
                tenantId.toString(), idempotencyKey, request));
    }

    @Transactional(readOnly = true)
    public ShotListJobView get(UUID tenantId, UUID projectId, UUID jobId) {
        ShotListJob job = shotListJobRepository.findById(jobId)
                .filter(j -> j.getTenantId().equals(tenantId) && j.getProjectId().equals(projectId))
                .orElseThrow(() -> PreProductionException.notFound(
                        "No shot-list job " + jobId + " for project " + projectId));
        return ShotListJobView.from(job);
    }

    /** Latest shot-list job for this project, or empty if none was ever submitted. Used by the UI
     * on mount to rehydrate a prior FAILED (or still-PENDING) run: without it, the section shows
     * the same empty-shot-list panel a fresh project shows, hiding both the reason for the empty
     * state and the fact that a generation was already attempted. Enforces the tenant scope. */
    @Transactional(readOnly = true)
    public Optional<ShotListJobView> latest(UUID tenantId, UUID projectId) {
        return shotListJobRepository.findTopByProjectIdAndTenantIdOrderByCreatedAtDesc(projectId, tenantId)
                .map(ShotListJobView::from);
    }

    private ShotListJob createPending(UUID tenantId, UUID projectId, String idempotencyKey) {
        OffsetDateTime now = OffsetDateTime.now();
        try {
            return shotListJobRepository.save(ShotListJob.builder()
                    .tenantId(tenantId)
                    .projectId(projectId)
                    .status(ShotListJobStatus.PENDING)
                    .llmJobIdempotencyKey(idempotencyKey)
                    .createdAt(now)
                    .updatedAt(now)
                    .build());
        } catch (DataIntegrityViolationException ex) {
            // Race: another request just inserted the same idempotency key between our findBy()
            // and this save(). The UNIQUE index on llm_job_idempotency_key caught it. Re-read
            // the row the racing request just wrote and treat it exactly like an already-existing
            // pending job -- one Kafka message eventually goes out either way, and the second
            // caller reuses the winner's job id. Prevents the "clicked twice, got a 500 the
            // second time and a duplicate job the first time" pattern.
            log.info("Idempotency-key race on shot-list submit -- reusing winner's row idempotencyKey={}",
                    idempotencyKey);
            return shotListJobRepository.findByLlmJobIdempotencyKey(idempotencyKey)
                    .map(existing -> resubmitIfTerminal(existing, tenantId))
                    .orElseThrow(() -> PreProductionException.upstream(
                            "Idempotency race resolved but row disappeared for key " + idempotencyKey));
        }
    }

    /** For a job row whose previous run finished terminally, reset it to PENDING and reuse the
     * row rather than inserting a duplicate -- the UNIQUE index on {@code llm_job_idempotency_key}
     * would reject the second insert anyway. For a job still PENDING, hand back the existing row
     * unchanged so a page-reload during an in-flight run doesn't kick off a second Kafka message
     * for the same work. */
    private ShotListJob resubmitIfTerminal(ShotListJob existing, UUID tenantId) {
        if (!existing.getTenantId().equals(tenantId)) {
            throw PreProductionException.badRequest(
                    "Shot-list job idempotency key already exists for a different tenant");
        }
        if (existing.getStatus() == ShotListJobStatus.PENDING) {
            log.info("Shot-list job jobId={} still PENDING -- reusing existing submission", existing.getId());
            return existing;
        }
        existing.setStatus(ShotListJobStatus.PENDING);
        existing.setErrorMessage(null);
        existing.setCompletedAt(null);
        existing.setUpdatedAt(OffsetDateTime.now());
        return shotListJobRepository.save(existing);
    }
}
