package com.dalai.llama.pbx.core.provision;

import com.dalai.llama.pbx.core.dto.TenantProvisioningRequest;
import com.dalai.llama.pbx.core.model.SignalingConfig;
import com.dalai.llama.pbx.core.model.Tenant;
import com.dalai.llama.pbx.core.repository.SignalingConfigRepository;
import com.dalai.llama.pbx.core.repository.TenantRepository;
import com.dalai.llama.pbx.core.util.TemplateRenderer;
import com.dalai.llama.pbx.core.util.KamailioConfigBuilder;
import com.dalai.llama.pbx.core.util.DomainNamer;
import com.dalai.llama.pbx.core.orchestration.SignalingOrchestratorService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class ProvisioningService {

    private final SignalingConfigRepository repo;
    private final TenantRepository tenantRepo;
    private final TemplateRenderer renderer;
    private final KamailioConfigBuilder kamBuilder;
    private final SignalingOrchestratorService orchestrator;

    @Value("${registry.container}")
    private String imageRegistry;
    @Value("${pbx.core.url}")
    private String pbxCoreInternalUrl;

    // base templates for coturn & rtpengine
    private static final String COTURN_TEMPLATE = """
# Autogenerated coturn fragment for ${TENANT_ID}
realm=${REALM}
external-ip=${EXTERNAL_IP}
fingerprint
""";

    private static final String RTPENGINE_TEMPLATE = """
# Autogenerated RTPengine config for ${TENANT_ID}
table=0
listen-ng=0.0.0.0:22222
listen-tcp=0.0.0.0:22222
listen-udp=0.0.0.0:10000
timeout=60
log-level=6
log-stderr
""";

    public SignalingConfig upsert(String tenantId, TenantProvisioningRequest req) {
        Tenant tenant = tenantRepo.findById(tenantId).orElseThrow();
        tenant.setStatus("provisioning");

        // 1️⃣ Save AI feature toggles
        if (req.getAiFeatures() != null) {
            tenant.setAiRoutingEnabled(req.getAiFeatures().isRouting());
            tenant.setAiTranscriptionEnabled(req.getAiFeatures().isTranscription());
            tenant.setAiNoiseCancellationEnabled(req.getAiFeatures().isNoiseCancellation());
        }
        tenantRepo.save(tenant);

        // 2️⃣ Retrieve or create signaling config
        var cfg = repo.findByTenantId(tenantId).orElseGet(SignalingConfig::new);
        cfg.setTenantId(tenantId);
        cfg.setAuthRealm(req.getAuthRealm());
        cfg.setDispatcherTargets(Collections.singletonList(String.join(",", req.getDispatcherTargets())));
        cfg.setTurnRealm(req.getTurnRealm());
        cfg.setTurnPolicy(req.getTurnPolicy());
        cfg.setTurnPortRange(req.getTurnPortRange());
        cfg.setWssUrl(req.getWssUrl());
        cfg.setStunUrls(Collections.singletonList(String.join(",", req.getStunUrls())));
        cfg.setTurnUrls(Collections.singletonList(String.join(",", req.getTurnUrls())));
        cfg.setUpdatedAt(Instant.now());
        cfg.setVersion(cfg.getVersion() == null ? 1 : cfg.getVersion() + 1);

        // 3️⃣ SBC (Kamailio + RTPengine + CoTURN)
        cfg.setEnableRtpEngine(true);
        cfg.setEnableTurn(true);
        boolean sbcEnabled = true;

        // 4️⃣ Tenant-specific FQDNs
        String client = (req.getClientName() == null || req.getClientName().isBlank())
                ? tenant.getName() : req.getClientName();
        String sipFqdn = DomainNamer.clientDns("sip", client, req.getAuthRealm());
        String pbxFqdn = DomainNamer.clientDns("pbx", client, req.getAuthRealm());
        String turnFqdn = DomainNamer.clientDns("turn", client, req.getAuthRealm());
        String wssFqdn = DomainNamer.clientDns("wss", client, req.getAuthRealm());
        cfg.setSipFqdn(sipFqdn);
        cfg.setPbxFqdn(pbxFqdn);
        cfg.setTurnFqdn(turnFqdn);
        cfg.setWssFqdn(wssFqdn);
        repo.save(cfg);

        // 5️⃣ Common vars for all templates
        Map<String, String> vars = new HashMap<>();
        vars.put("TENANT_ID", tenantId);
        vars.put("REALM", req.getAuthRealm() == null ? "" : req.getAuthRealm());
        vars.put("SBC_ENABLED", String.valueOf(sbcEnabled));
        vars.put("EXTERNAL_IP", cfg.getTurnFqdn());
        vars.put("AI_FEATURES", buildAiHeader(tenant));
        vars.put("AI_IMAGE", imageRegistry + "/ai-service:latest");
        vars.put("AGENT_IMAGE", imageRegistry + "/agent-service:latest");
        vars.put("KAMAILIO_IMAGE", imageRegistry + "/kamailio:latest");
        vars.put("COTURN_IMAGE", imageRegistry + "/coturn:latest");
        vars.put("RTPENGINE_IMAGE", imageRegistry + "/rtpengine:latest");
        vars.put("RTP2KAFKA_IMAGE", imageRegistry + "/rtp2kafka:latest");
        // --- NEW: Define PBX_CORE_URL for Kamailio ---
        // Assuming your PBX Core runs on the pbxFqdn at port 8080 (adjust port if needed)
        String pbxCoreUrl = pbxCoreInternalUrl;
        // 6️⃣ Build configs using TemplateRenderer and KamailioConfigBuilder
        String kamailioCoreCfg = kamBuilder.build(tenant, cfg); // <--- FIXED: actually use it
        String turnCfg = renderer.render(COTURN_TEMPLATE, vars);
        String rtpCfg = renderer.render(RTPENGINE_TEMPLATE, vars);

        // Combine kamBuilder config with runtime vars (add top header)
        String kamailioFullCfg = String.format("""
# =============================================
# Kamailio autogenerated config for tenant %s
# =============================================
#!define TENANT_REALM %s
#!define SBC_ENABLED %s
#!define RTPENGINE_SOCK udp:rtpengine-%s:22222
#!define PBX_CORE_URL "%s"
%s
""", tenantId, cfg.getAuthRealm(), sbcEnabled, tenantId,pbxCoreUrl, kamailioCoreCfg);

        // 7️⃣ Persist configs locally
        String basePath = "/tmp/pbx-config/" + tenantId;
        renderer.writeFile(basePath + "/kamailio/kamailio-" + tenantId + ".cfg", kamailioFullCfg);
        renderer.writeFile(basePath + "/coturn/coturn-" + tenantId + ".conf", turnCfg);
        renderer.writeFile(basePath + "/rtpengine/rtpengine-" + tenantId + ".conf", rtpCfg);

        // 8️⃣ Launch the SBC & AI stack
        tenant = orchestrator.launchStackWithConfig(tenant, cfg, client, kamailioFullCfg);
        orchestrator.ensureHealth(tenant);

        tenant.setStatus("active");
        tenantRepo.save(tenant);
        return cfg;
    }

    private String buildAiHeader(Tenant t) {
        java.util.List<String> flags = new java.util.ArrayList<>();
        if (t.isAiTranscriptionEnabled()) flags.add("transcription");
        if (t.isAiNoiseCancellationEnabled()) flags.add("noise-cancel");
        if (t.isAiRoutingEnabled()) flags.add("routing");
        return flags.isEmpty() ? "none" : String.join(",", flags);
    }
}
