package com.dalai.llama.pbx.core.provision;

import com.dalai.llama.pbx.core.dto.TenantProvisioningRequest;
import com.dalai.llama.pbx.core.model.*;
import com.dalai.llama.pbx.core.repository.*;
import com.dalai.llama.pbx.core.util.TemplateRenderer;
import com.dalai.llama.pbx.core.util.KamailioConfigBuilder;
import com.dalai.llama.pbx.core.util.DomainNamer;
import com.dalai.llama.pbx.core.orchestration.SignalingOrchestratorService;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.*;

@Service
@RequiredArgsConstructor
public class ProvisioningService {

    private final SignalingConfigRepository repo;
    private final TenantRepository tenantRepo;
    private final TrunkRepository trunkRepo;
    private final DidRepository didRepo;

    private final TemplateRenderer renderer;
    private final KamailioConfigBuilder kamBuilder;
    private final SignalingOrchestratorService orchestrator;

    @Value("${registry.container}")
    private String imageRegistry;

    @Value("${pbx.core.url}")
    private String pbxCoreInternalUrl;

    private static final String COTURN_TEMPLATE = """
# Autogenerated coturn fragment for ${TENANT_ID}
realm=${REALM}
external-ip=${EXTERNAL_IP}
fingerprint
""";

    private static final String RTPENGINE_TEMPLATE = """
# Autogenerated RTPengine config for ${TENANT_ID}
table=0
listen-ng=0.0.0.0:22222
listen-tcp=0.0.0.0:22222
listen-udp=0.0.0.0:10000
timeout=60
log-level=6
log-stderr
""";

    public SignalingConfig upsert(String tenantId, TenantProvisioningRequest req) {

        // ----------------------------------------------------
        // 1️⃣ Load Tenant
        // ----------------------------------------------------
        Tenant tenant = tenantRepo.findById(tenantId).orElseThrow();
        tenant.setStatus("provisioning");

        // Save AI toggles
        if (req.getAiFeatures() != null) {
            tenant.setAiRoutingEnabled(req.getAiFeatures().isRouting());
            tenant.setAiTranscriptionEnabled(req.getAiFeatures().isTranscription());
            tenant.setAiNoiseCancellationEnabled(req.getAiFeatures().isNoiseCancellation());
        }
        tenantRepo.save(tenant);

        // ----------------------------------------------------
        // 2️⃣ AUTO-LOAD Trunks & DIDs for this tenant
        // ----------------------------------------------------
        List<Trunk> trunks = trunkRepo.findByTenantIdAndEnabledTrue(tenantId);
        List<Did> dids = didRepo.findByTenantIdAndStatus(tenantId, "active");

        // ----------------------------------------------------
        // 3️⃣ Auto-generate dispatcher targets from trunks
        // ----------------------------------------------------
        List<String> dispatcherTargets = trunks.stream()
                .filter(Trunk::isEnabled)
                .map(t -> t.getSipUri())       // use SIP URI as target
                .toList();

        // ----------------------------------------------------
        // 4️⃣ Populate SignalingConfig (minimal UI input)
        // ----------------------------------------------------
        SignalingConfig cfg = repo.findByTenantId(tenantId).orElseGet(SignalingConfig::new);

        cfg.setTenantId(tenantId);
        cfg.setAuthRealm(req.getAuthRealm());
        cfg.setDispatcherTargets(dispatcherTargets);

        // TURN defaults (auto generated)
        cfg.setTurnRealm(req.getAuthRealm());
        cfg.setTurnPolicy("static-auth");
        cfg.setTurnPortRange("10000-20000");

        // WSS defaults
        cfg.setWssUrl("wss://" + DomainNamer.clientDns("wss", tenant.getName(), req.getAuthRealm()));

        cfg.setStunUrls(List.of("stun:" + DomainNamer.clientDns("turn", tenant.getName(), req.getAuthRealm()) + ":3478"));
        cfg.setTurnUrls(List.of("turn:" + DomainNamer.clientDns("turn", tenant.getName(), req.getAuthRealm()) + ":3478"));

        cfg.setUpdatedAt(Instant.now());
        cfg.setVersion(cfg.getVersion() == null ? 1 : cfg.getVersion() + 1);

        cfg.setEnableRtpEngine(true);
        cfg.setEnableTurn(true);
        cfg.setSbcEnabled(true);

        // ----------------------------------------------------
        // 5️⃣ Generate tenant-specific FQDNs
        // ----------------------------------------------------
        String client = (req.getClientName() == null || req.getClientName().isBlank())
                ? tenant.getName()
                : req.getClientName();

        cfg.setSipFqdn(DomainNamer.clientDns("sip", client, req.getAuthRealm()));
        cfg.setPbxFqdn(DomainNamer.clientDns("pbx", client, req.getAuthRealm()));
        cfg.setTurnFqdn(DomainNamer.clientDns("turn", client, req.getAuthRealm()));
        cfg.setWssFqdn(DomainNamer.clientDns("wss", client, req.getAuthRealm()));

        repo.save(cfg);

        // ----------------------------------------------------
        // 6️⃣ Build vars for template rendering
        // ----------------------------------------------------
        Map<String, String> vars = new HashMap<>();
        vars.put("TENANT_ID", tenantId);
        vars.put("REALM", req.getAuthRealm());
        vars.put("SBC_ENABLED", "true");
        vars.put("EXTERNAL_IP", cfg.getTurnFqdn());
        vars.put("AI_FEATURES", buildAiHeader(tenant));

        vars.put("AI_IMAGE", imageRegistry + "/ai-service:latest");
        vars.put("AGENT_IMAGE", imageRegistry + "/agent-service:latest");
        vars.put("KAMAILIO_IMAGE", imageRegistry + "/dalaillama-kamailio:latest");
        vars.put("COTURN_IMAGE", imageRegistry + "/dalaillama-coturn:latest");
        vars.put("RTPENGINE_IMAGE", imageRegistry + "/dalaillama-rtpengine:latest");
        vars.put("RTP2KAFKA_IMAGE", imageRegistry + "/dalaillama-rtp2kafka:latest");

        // ----------------------------------------------------
        // 7️⃣ PBX Core URL for ingress routing
        // ----------------------------------------------------
        String pbxCoreUrl = pbxCoreInternalUrl;

        // ----------------------------------------------------
        // 8️⃣ Build SBC configs
        // ----------------------------------------------------
        String kamailioCoreCfg = kamBuilder.build(tenant, cfg, trunks, dids);

        String kamailioFullCfg = String.format("""
# =============================================
# Kamailio autogenerated config for tenant %s
# =============================================
#!define TENANT_REALM %s
#!define SBC_ENABLED %s
#!define RTPENGINE_SOCK udp:rtpengine-%s:22222
#!define PBX_CORE_URL "%s"
%s
""", tenantId, cfg.getAuthRealm(), true, tenantId, pbxCoreUrl, kamailioCoreCfg);

        String turnCfg = renderer.render(COTURN_TEMPLATE, vars);
        String rtpCfg = renderer.render(RTPENGINE_TEMPLATE, vars);

        String basePath = "/tmp/pbx-config/" + tenantId;
        renderer.writeFile(basePath + "/kamailio/kamailio-" + tenantId + ".cfg", kamailioFullCfg);
        renderer.writeFile(basePath + "/coturn/coturn-" + tenantId + ".conf", turnCfg);
        renderer.writeFile(basePath + "/rtpengine/rtpengine-" + tenantId + ".conf", rtpCfg);

        // ----------------------------------------------------
        // 9️⃣ Launch SBC stack (Kamailio+TURN+RTP)
        // ----------------------------------------------------
        tenant = orchestrator.launchStackWithConfig(tenant, cfg, client, kamailioFullCfg);

        orchestrator.ensureHealth(tenant);

        tenant.setStatus("active");
        tenantRepo.save(tenant);

        return cfg;
    }

    private String buildAiHeader(Tenant t) {
        List<String> flags = new ArrayList<>();
        if (t.isAiTranscriptionEnabled()) flags.add("transcription");
        if (t.isAiNoiseCancellationEnabled()) flags.add("noise-cancel");
        if (t.isAiRoutingEnabled()) flags.add("routing");
        return flags.isEmpty() ? "none" : String.join(",", flags);
    }
}
