name: Build and deploy JAR app to Azure Web App - dalai-llama-backend
on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: List target directory contents
        run: ls -la ${{ github.workspace }}/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
          retention-days: 1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded artifacts
        run: ls -la

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49246DA21BF143A79A5EF0ED6B3A15D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C39EF57EB4B44B184C03F29057D979E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_92FAC193FEAD43A8B8B77E8BEB73F517 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dalai-llama-backend'
          slot-name: 'Production'
          package: '**/*.jar'